<?php
/**
 * Seeds the built-in compliance frameworks. Each is a checklist a tech assesses per client;
 * they are summaries for tracking, not legal text. Edit or extend under Compliance > Frameworks.
 *
 * auto_check links a control to a device-data indicator shown beside it:
 *   os_supported | hw_lifecycle | warranty | stale
 */
declare(strict_types=1);

use Align\DB;

return function (): void {
    $frameworks = [
        [
            'slug' => 'msp-baseline',
            'name' => 'MSP Security Baseline',
            'description' => 'A security standard for every managed client. Use it to spot gaps and drive the roadmap.',
            'controls' => [
                ['Identity', 'MSB-1', 'MFA enforced for Microsoft 365 / email for all users', 'Conditional Access or Security Defaults; no per-user exclusions without a documented reason.'],
                ['Identity', 'MSB-2', 'MFA required for all remote access (VPN, RDP gateways, remote tools)', null],
                ['Identity', 'MSB-3', 'Separate admin accounts; daily-use accounts have no admin rights', null],
                ['Identity', 'MSB-4', 'Local admin rights removed from end users', null],
                ['Identity', 'MSB-5', 'Business password manager deployed for staff', null],
                ['Identity', 'MSB-6', 'Documented onboarding/offboarding; departed users disabled same day', null],
                ['Endpoints', 'MSB-7', 'EDR / next-gen antivirus on every workstation and server', null],
                ['Endpoints', 'MSB-8', 'OS patches applied automatically within 14 days (critical within 7)', null],
                ['Endpoints', 'MSB-9', 'Third-party applications patched automatically', null],
                ['Endpoints', 'MSB-10', 'All devices run a vendor-supported operating system', null, 'os_supported'],
                ['Endpoints', 'MSB-11', 'Full-disk encryption on laptops (BitLocker / FileVault)', null],
                ['Endpoints', 'MSB-12', 'Hardware within lifecycle policy', null, 'hw_lifecycle'],
                ['Endpoints', 'MSB-13', 'All managed devices checking in to RMM', null, 'stale'],
                ['Backup & recovery', 'MSB-14', 'Servers and cloud data (M365) backed up daily', null],
                ['Backup & recovery', 'MSB-15', 'At least one backup copy is offsite and immutable or offline', null],
                ['Backup & recovery', 'MSB-16', 'Restore tested and documented in the last 6 months', null],
                ['Network', 'MSB-17', 'Business-class firewall with current firmware and active support', null, 'warranty'],
                ['Network', 'MSB-18', 'No RDP or admin interfaces exposed to the internet', null],
                ['Network', 'MSB-19', 'Guest Wi-Fi isolated from the business network', null],
                ['Network', 'MSB-20', 'DNS / web filtering on all endpoints', null],
                ['Email', 'MSB-21', 'Advanced email filtering (phishing, malware, impersonation)', null],
                ['Email', 'MSB-22', 'SPF, DKIM and DMARC configured (DMARC at quarantine or reject)', null],
                ['People & process', 'MSB-23', 'Security awareness training at least annually', null],
                ['People & process', 'MSB-24', 'Phishing simulations run at least quarterly', null],
                ['People & process', 'MSB-25', 'Written incident response plan with contacts, reviewed yearly', null],
                ['People & process', 'MSB-26', 'Wire/payment change requests verified by phone call-back', null],
            ],
        ],
        [
            'slug' => 'cyber-insurance',
            'name' => 'Cyber Insurance Readiness',
            'description' => 'Questions most cyber insurance applications ask. Wording varies by carrier; use this to prepare answers and close gaps before renewal.',
            'controls' => [
                ['Access', 'CI-1', 'MFA on email for all users', null],
                ['Access', 'CI-2', 'MFA on all remote network access', null],
                ['Access', 'CI-3', 'MFA on privileged / administrator accounts', null],
                ['Access', 'CI-4', 'Remote Desktop (RDP) not exposed to the internet', null],
                ['Access', 'CI-5', 'Privileged accounts inventoried and limited to those who need them', null],
                ['Detection', 'CI-6', 'EDR deployed on all endpoints and servers', null],
                ['Detection', 'CI-7', '24/7 monitoring of security alerts (MDR / SOC)', null],
                ['Detection', 'CI-8', 'Advanced email filtering in place', null],
                ['Backups', 'CI-9', 'Backups kept offline, immutable, or otherwise separated from the network', null],
                ['Backups', 'CI-10', 'Backups encrypted', null],
                ['Backups', 'CI-11', 'Backup restoration tested at least annually', null],
                ['Maintenance', 'CI-12', 'Critical patches applied within 30 days', null],
                ['Maintenance', 'CI-13', 'No end-of-life / unsupported software or operating systems', null, 'os_supported'],
                ['People', 'CI-14', 'Annual security awareness training', null],
                ['People', 'CI-15', 'Regular phishing simulations', null],
                ['Process', 'CI-16', 'Funds-transfer requests verified out of band (call-back procedure)', null],
                ['Process', 'CI-17', 'Written incident response plan', null],
                ['Process', 'CI-18', 'Vendor and third-party remote access controlled and logged', null],
                ['Process', 'CI-19', 'Sensitive data (PII / PHI / payment data) identified and encrypted', null],
            ],
        ],
        [
            'slug' => 'cis-v8-ig1',
            'name' => 'CIS Controls v8 — IG1',
            'description' => 'Implementation Group 1 ("essential cyber hygiene"): the 56 safeguards CIS recommends every organization implement. Titles are MSP Align\'s own summaries, not CIS text; refs are the CIS safeguard numbers. CIS Controls® is a registered trademark of the Center for Internet Security, Inc.; no affiliation or endorsement.',
            'controls' => [
                ['1 Inventory of Enterprise Assets', '1.1', 'Keep a detailed, current inventory of all enterprise assets', null],
                ['1 Inventory of Enterprise Assets', '1.2', 'Deal with unauthorized assets', null],
                ['2 Inventory of Software Assets', '2.1', 'Keep a current software inventory', null],
                ['2 Inventory of Software Assets', '2.2', 'Make sure authorized software is still vendor-supported', null, 'os_supported'],
                ['2 Inventory of Software Assets', '2.3', 'Deal with unauthorized software', null],
                ['3 Data Protection', '3.1', 'Maintain a data management process', null],
                ['3 Data Protection', '3.2', 'Maintain a data inventory', null],
                ['3 Data Protection', '3.3', 'Set access control lists on data', null],
                ['3 Data Protection', '3.4', 'Keep data only as long as the retention policy allows', null],
                ['3 Data Protection', '3.5', 'Dispose of data securely', null],
                ['3 Data Protection', '3.6', 'Encrypt laptops and other end-user devices', null],
                ['4 Secure Configuration', '4.1', 'Maintain a secure configuration process', null],
                ['4 Secure Configuration', '4.2', 'Maintain a secure configuration process for network gear', null],
                ['4 Secure Configuration', '4.3', 'Lock sessions automatically after inactivity', null],
                ['4 Secure Configuration', '4.4', 'Run and manage a firewall on servers', null],
                ['4 Secure Configuration', '4.5', 'Run and manage a firewall on end-user devices', null],
                ['4 Secure Configuration', '4.6', 'Manage assets and software securely', null],
                ['4 Secure Configuration', '4.7', 'Manage default accounts', null],
                ['5 Account Management', '5.1', 'Maintain an inventory of accounts', null],
                ['5 Account Management', '5.2', 'Require a different password for every account', null],
                ['5 Account Management', '5.3', 'Turn off accounts unused for 45 days', null],
                ['5 Account Management', '5.4', 'Keep admin rights on dedicated admin accounts', null],
                ['6 Access Control Management', '6.1', 'Have a process for granting access', null],
                ['6 Access Control Management', '6.2', 'Have a process for revoking access', null],
                ['6 Access Control Management', '6.3', 'Require MFA on externally exposed applications', null],
                ['6 Access Control Management', '6.4', 'Use MFA for VPN and other remote access', null],
                ['6 Access Control Management', '6.5', 'Use MFA for every admin sign-in', null],
                ['7 Continuous Vulnerability Management', '7.1', 'Maintain a vulnerability management process', null],
                ['7 Continuous Vulnerability Management', '7.2', 'Maintain a remediation process', null],
                ['7 Continuous Vulnerability Management', '7.3', 'Automate operating system patching', null],
                ['7 Continuous Vulnerability Management', '7.4', 'Automate application patching', null],
                ['8 Audit Log Management', '8.1', 'Maintain an audit log management process', null],
                ['8 Audit Log Management', '8.2', 'Turn on audit logging', null],
                ['8 Audit Log Management', '8.3', 'Provide enough audit log storage', null],
                ['9 Email and Web Browser Protections', '9.1', 'Use only fully supported browsers and email clients', null],
                ['9 Email and Web Browser Protections', '9.2', 'Use DNS filtering', null],
                ['10 Malware Defenses', '10.1', 'Run anti-malware on every device', null],
                ['10 Malware Defenses', '10.2', 'Update anti-malware signatures automatically', null],
                ['10 Malware Defenses', '10.3', 'Turn off autorun for USB drives and other removable media', null],
                ['11 Data Recovery', '11.1', 'Maintain a data recovery process', null],
                ['11 Data Recovery', '11.2', 'Run automated backups', null],
                ['11 Data Recovery', '11.3', 'Secure backups as carefully as the data they hold', null],
                ['11 Data Recovery', '11.4', 'Keep an isolated copy of recovery data', null],
                ['12 Network Infrastructure Management', '12.1', 'Keep network infrastructure up to date', null, 'warranty'],
                ['14 Security Awareness and Skills Training', '14.1', 'Maintain a security awareness program', null],
                ['14 Security Awareness and Skills Training', '14.2', 'Train staff to recognize social engineering', null],
                ['14 Security Awareness and Skills Training', '14.3', 'Train staff on authentication best practices', null],
                ['14 Security Awareness and Skills Training', '14.4', 'Train staff on data handling', null],
                ['14 Security Awareness and Skills Training', '14.5', 'Train staff on causes of accidental data exposure', null],
                ['14 Security Awareness and Skills Training', '14.6', 'Train staff to recognize and report incidents', null],
                ['14 Security Awareness and Skills Training', '14.7', 'Train staff to spot and report missing security updates', null],
                ['14 Security Awareness and Skills Training', '14.8', 'Train staff on risks of insecure networks', null],
                ['15 Service Provider Management', '15.1', 'Maintain an inventory of service providers', null],
                ['17 Incident Response Management', '17.1', 'Name the people who handle incidents', null],
                ['17 Incident Response Management', '17.2', 'Keep contact information for reporting incidents', null],
                ['17 Incident Response Management', '17.3', 'Maintain a process for staff to report incidents', null],
            ],
        ],
        [
            'slug' => 'hipaa-security',
            'name' => 'HIPAA Security Rule',
            'description' => 'Standards and implementation specifications from 45 CFR 164.308, 164.310 and 164.312, summarized. (R) = required, (A) = addressable. HHS has proposed updates to the Security Rule, so check for changes. This checklist is not legal advice.',
            'controls' => [
                ['Administrative safeguards', '164.308(a)(1)(ii)(A)', 'Risk analysis (R)', 'Accurate and thorough assessment of risks to ePHI.'],
                ['Administrative safeguards', '164.308(a)(1)(ii)(B)', 'Risk management (R)', 'Security measures to reduce risks to a reasonable level.'],
                ['Administrative safeguards', '164.308(a)(1)(ii)(C)', 'Sanction policy (R)', null],
                ['Administrative safeguards', '164.308(a)(1)(ii)(D)', 'Information system activity review (R)', 'Regular review of audit logs, access reports and incident tracking.'],
                ['Administrative safeguards', '164.308(a)(2)', 'Assigned security responsibility (R)', 'A named security official.'],
                ['Administrative safeguards', '164.308(a)(3)(ii)(A)', 'Workforce authorization and/or supervision (A)', null],
                ['Administrative safeguards', '164.308(a)(3)(ii)(B)', 'Workforce clearance procedure (A)', null],
                ['Administrative safeguards', '164.308(a)(3)(ii)(C)', 'Termination procedures (A)', null],
                ['Administrative safeguards', '164.308(a)(4)(ii)(B)', 'Access authorization (A)', null],
                ['Administrative safeguards', '164.308(a)(4)(ii)(C)', 'Access establishment and modification (A)', null],
                ['Administrative safeguards', '164.308(a)(5)(ii)(A)', 'Security reminders (A)', null],
                ['Administrative safeguards', '164.308(a)(5)(ii)(B)', 'Protection from malicious software (A)', null],
                ['Administrative safeguards', '164.308(a)(5)(ii)(C)', 'Log-in monitoring (A)', null],
                ['Administrative safeguards', '164.308(a)(5)(ii)(D)', 'Password management (A)', null],
                ['Administrative safeguards', '164.308(a)(6)(ii)', 'Security incident response and reporting (R)', null],
                ['Administrative safeguards', '164.308(a)(7)(ii)(A)', 'Data backup plan (R)', null],
                ['Administrative safeguards', '164.308(a)(7)(ii)(B)', 'Disaster recovery plan (R)', null],
                ['Administrative safeguards', '164.308(a)(7)(ii)(C)', 'Emergency mode operation plan (R)', null],
                ['Administrative safeguards', '164.308(a)(7)(ii)(D)', 'Contingency plan testing and revision (A)', null],
                ['Administrative safeguards', '164.308(a)(7)(ii)(E)', 'Applications and data criticality analysis (A)', null],
                ['Administrative safeguards', '164.308(a)(8)', 'Periodic technical and non-technical evaluation (R)', null],
                ['Administrative safeguards', '164.308(b)(1)', 'Business associate agreements in place (R)', 'Including with the MSP and cloud vendors that handle ePHI.'],
                ['Physical safeguards', '164.310(a)(2)(i)', 'Facility contingency operations (A)', null],
                ['Physical safeguards', '164.310(a)(2)(ii)', 'Facility security plan (A)', null],
                ['Physical safeguards', '164.310(a)(2)(iii)', 'Facility access control and validation procedures (A)', null],
                ['Physical safeguards', '164.310(a)(2)(iv)', 'Maintenance records for facility security repairs (A)', null],
                ['Physical safeguards', '164.310(b)', 'Workstation use policy (R)', null],
                ['Physical safeguards', '164.310(c)', 'Workstation security — physical safeguards (R)', null],
                ['Physical safeguards', '164.310(d)(2)(i)', 'Disposal of ePHI and hardware (R)', null],
                ['Physical safeguards', '164.310(d)(2)(ii)', 'Media re-use — ePHI removed before re-use (R)', null],
                ['Physical safeguards', '164.310(d)(2)(iii)', 'Hardware and media accountability (A)', null, 'hw_lifecycle'],
                ['Physical safeguards', '164.310(d)(2)(iv)', 'Data backup and storage before equipment moves (A)', null],
                ['Technical safeguards', '164.312(a)(2)(i)', 'Unique user identification (R)', null],
                ['Technical safeguards', '164.312(a)(2)(ii)', 'Emergency access procedure (R)', null],
                ['Technical safeguards', '164.312(a)(2)(iii)', 'Automatic logoff (A)', null],
                ['Technical safeguards', '164.312(a)(2)(iv)', 'Encryption and decryption of ePHI at rest (A)', null],
                ['Technical safeguards', '164.312(b)', 'Audit controls (R)', null],
                ['Technical safeguards', '164.312(c)(2)', 'Mechanism to authenticate ePHI integrity (A)', null],
                ['Technical safeguards', '164.312(d)', 'Person or entity authentication (R)', null],
                ['Technical safeguards', '164.312(e)(2)(i)', 'Transmission integrity controls (A)', null],
                ['Technical safeguards', '164.312(e)(2)(ii)', 'Transmission encryption (A)', null],
            ],
        ],
    ];

    foreach ($frameworks as $fw) {
        if (DB::value('SELECT id FROM compliance_frameworks WHERE slug = ?', [$fw['slug']])) {
            continue;
        }
        $fid = DB::insert('compliance_frameworks', [
            'slug' => $fw['slug'],
            'name' => $fw['name'],
            'description' => $fw['description'],
            'is_builtin' => 1,
        ]);
        foreach ($fw['controls'] as $i => $c) {
            DB::insert('compliance_controls', [
                'framework_id' => $fid,
                'section' => $c[0],
                'ref' => $c[1],
                'title' => $c[2],
                'guidance' => $c[3] ?? null,
                'auto_check' => $c[4] ?? null,
                'sort' => ($i + 1) * 10,
            ]);
        }
    }
};
