<?php
// Example config for development. Production config is generated by install.sh
// at /etc/msp-align/config.php. Generate a key with:
//   php -r 'echo "base64:" . base64_encode(random_bytes(32)), PHP_EOL;'
return [
    'db' => [
        'host' => 'localhost',
        'name' => 'msp_align',
        'user' => 'align',
        'pass' => 'change-me',
    ],
    'app_key' => 'base64:REPLACE_WITH_32_RANDOM_BYTES_BASE64',
    'base_url' => 'http://127.0.0.1:8080',
    'timezone' => 'America/Los_Angeles',
    'trusted_proxies' => [],
    'session_path' => null,
    'php_cli' => '/usr/bin/php',
    'debug' => true,          // never true in production: shows error details
    // Development only: allow an http:// ITFlow URL (e.g. a local mock). Production requires https://.
    'allow_insecure_integrations' => false,
    // Where updates come from: 'main' (releases) or, on a test server, 'develop'
    'update_branch' => 'main',
    // Optional: check a small version file before asking GitHub (GitHub is still used to download updates)
    // 'update_check_url' => 'https://mspalign.org/updates',
    // Test server on a copy of production data (docs/TEST-SERVER.md): reads from connected tools still
    // work, nothing is written back, all email goes to one test mailbox, the portal and API are off.
    // 'staging' => true,
    // 'staging_mail_to' => 'align-test@example.com',
];
