<?php
/**
 * California Consumer Privacy Act as amended by the CPRA (Civ. Code 1798.100 et seq.) and the CPPA
 * regulations (Cal. Code Regs., tit. 11, § 7000 et seq.), including the cybersecurity audit, risk
 * assessment and ADMT regulations approved Sept. 22, 2025 (effective Jan. 1, 2026).
 * Statute and regulations are public domain. Summary for tracking an assessment, not legal advice.
 */
return [
    'slug' => 'ccpa-cpra',
    'name' => 'California CCPA / CPRA',
    'description' => 'Practical checklist for the California Consumer Privacy Act as amended by the CPRA (Civ. Code 1798.100 et seq.) and the CPPA regulations (11 CCR 7000 et seq.). '
        . 'Applies to for-profit businesses that do business in California and meet one threshold: annual gross revenue above the CPI-adjusted figure ($26,625,000 since Jan. 1, 2025; next adjustment Jan. 2027), '
        . 'buying/selling/sharing personal information of 100,000+ consumers or households, or earning 50%+ of revenue from selling or sharing personal information. Employee and B2B data are fully in scope. '
        . 'Key 2025–2026 changes: regulations approved Sept. 2025 and effective Jan. 1, 2026 add risk assessments (existing processing assessed by Dec. 31, 2027; first attestation due Apr. 1, 2028), '
        . 'annual independent cybersecurity audits for significant-risk businesses (first certifications due Apr. 1, 2028 / 2029 / 2030 by revenue tier), and ADMT rules (compliance by Jan. 1, 2027); '
        . 'SB 446 sets a 30-day breach notification deadline from Jan. 1, 2026. Most small MSP clients will not meet the thresholds; confirm applicability first and mark the rest N/A. '
        . 'This is a summary for tracking an assessment, not legal advice.',
    'controls' => [
        // ---- Applicability --------------------------------------------------------------
        ['Applicability', '1798.140(d)(1)(A)', 'Annual gross revenue in the prior calendar year exceeds the CPI-adjusted threshold ($26,625,000 since Jan. 1, 2025)', 'Record prior-year global gross revenue and the threshold in effect. The CPPA adjusts the figure every odd-numbered year, so recheck in January 2027.', null, ['gov_legal']],
        ['Applicability', '1798.140(d)(1)(B)', 'Alone or in combination, annually buys, sells or shares the personal information of 100,000 or more consumers or households', 'Count California consumers/households whose data is bought, sold or shared (including cross-context behavioral advertising via pixels and ad tech), not merely collected.', null, ['gov_legal', 'data_inventory']],
        ['Applicability', '1798.140(d)(1)(C)', 'Derives 50 percent or more of annual revenue from selling or sharing consumers\' personal information', null, null, ['gov_legal']],
        ['Applicability', '1798.145', 'Applicability determination and exemptions documented (e.g. HIPAA PHI, GLBA data, affiliates under common branding)', 'Written memo of which thresholds are met, which data sets are exempt, and the review date. Exemptions are data-level, not entity-level: a HIPAA or GLBA entity is still covered for its other personal information.', null, ['gov_legal', 'data_inventory']],

        // ---- Notices & policy -----------------------------------------------------------
        ['Notices & policy', '§7011', 'Online privacy policy contains all required disclosures and is reviewed and updated at least every 12 months', 'Covers categories collected, sources, purposes, disclosures, sale/sharing, retention periods, consumer rights (now including ADMT opt-out and access), how to submit requests, and the last-updated date (1798.130(a)(5)). Evidence: current policy URL and review log.', null, ['gov_privacy_notice']],
        ['Notices & policy', '§7012', 'Notice at collection is given at or before the point personal information is collected (online, in person, by phone, and to employees/applicants)', 'Lists categories of personal and sensitive information, purposes, whether it is sold or shared, and retention period, or links to the privacy policy section that does. Evidence: screenshots of web forms and the employee/applicant notice.', null, ['gov_privacy_notice']],
        ['Notices & policy', '§7013', 'Notice of right to opt out of sale/sharing and a "Do Not Sell or Share My Personal Information" link (or alternative opt-out link) if the business sells or shares', 'Mark N/A with a documented reason if the business does not sell or share personal information (check ad pixels and analytics tags).', null, ['gov_privacy_notice']],
        ['Notices & policy', '§7014', 'Notice of right to limit and a "Limit the Use of My Sensitive Personal Information" link if sensitive personal information is used beyond permitted purposes', 'Permitted purposes are listed in §7027(m); if SPI is used only for those, document that and mark N/A.', null, ['gov_privacy_notice']],
        ['Notices & policy', '§7016', 'Notice of financial incentive is provided before opting consumers into any loyalty program, discount or price difference tied to personal information', 'Include the material terms, how to opt in and withdraw, and a good-faith estimate of the value of the consumer\'s data and how it was calculated.', null, ['gov_privacy_notice']],

        // ---- Consumer requests ----------------------------------------------------------
        ['Consumer requests', '1798.110', 'Right to know/access: consumers can obtain the categories and specific pieces of personal information collected about them', 'Documented procedure to locate data across systems (email, file shares, CRM, line-of-business apps, backups as applicable) and deliver it in a portable format. Evidence: SOP and a completed sample request.', null, ['gov_privacy_notice', 'data_inventory']],
        ['Consumer requests', '1798.105', 'Right to delete: verified deletion requests are honored and passed on to service providers, contractors and third parties', 'Procedure covers exceptions (§7022), notifying downstream vendors, and how backups are handled (delete on restore). Evidence: SOP and deletion log.', null, ['gov_privacy_notice', 'data_retention_disposal']],
        ['Consumer requests', '1798.106', 'Right to correct: inaccurate personal information is corrected using commercially reasonable efforts', 'See §7023 for documentation the business may request and how to handle disputed accuracy.', null, ['gov_privacy_notice']],
        ['Consumer requests', '1798.120', 'Right to opt out of sale/sharing is honored within 15 business days and passed to third parties', 'Per §7026, stop selling/sharing and notify third parties who received the data; real-time bidding opt-outs must be honored immediately where feasible. Mark N/A if no sale or sharing.', null, ['gov_privacy_notice']],
        ['Consumer requests', '1798.121', 'Right to limit use and disclosure of sensitive personal information is honored within 15 business days', 'Per §7027. Mark N/A if SPI is used only for permitted purposes.', null, ['gov_privacy_notice']],
        ['Consumer requests', '§7021', 'Receipt of requests to know, delete or correct is confirmed within 10 business days and a response is given within 45 calendar days', 'One 45-day extension is allowed with notice and reasons. Evidence: request log showing received, confirmed and closed dates.', null, ['gov_privacy_notice']],
        ['Consumer requests', '§7060', 'Reasonable verification procedures confirm the identity of requestors and authorized agents', 'Match data points proportionate to the sensitivity of the request (§7062); do not require an account; verify authorized agent permission (§7063). Evidence: written verification procedure.', null, ['gov_privacy_notice']],
        ['Consumer requests', '§7020', 'At least two methods to submit requests to know/delete/correct, including a toll-free number (email allowed instead for online-only businesses with a direct relationship)', 'Opt-out and limit requests need their own easy methods (link or form). Evidence: screenshots of the web form, phone number and email address.', null, ['gov_privacy_notice']],
        ['Consumer requests', '§7025', 'Opt-out preference signals such as Global Privacy Control are honored as valid opt-out requests', 'Test the website with a GPC-enabled browser. Since Jan. 1, 2026 the site must display whether the signal was processed (§7025(c)(6)). Evidence: test screenshot and consent-tool configuration.', null, ['gov_privacy_notice', 'browser_controls']],
        ['Consumer requests', '1798.125', 'Consumers are not discriminated against for exercising their rights (no denial of goods, different prices or quality unless a compliant financial incentive)', 'Choice screens and cookie banners avoid dark patterns and offer symmetrical choices (§7004). See also §7080.', null, ['gov_privacy_notice']],
        ['Consumer requests', '§7101', 'Records of consumer requests and responses are kept for at least 24 months', 'Log date, request type, verification outcome, response date and basis for any denial. Protect the log with reasonable security and do not use it for other purposes.', null, ['gov_privacy_notice', 'log_retention']],
        ['Consumer requests', '§7100', 'Everyone who handles consumer inquiries or privacy compliance is trained on CCPA requirements and how to direct consumers to exercise their rights', 'Evidence: training materials and completion records for front desk, customer service and privacy staff.', null, ['awareness_training', 'gov_privacy_notice']],

        // ---- Contracts ------------------------------------------------------------------
        ['Contracts', '1798.100(d)', 'Inventory of service providers, contractors and third parties that receive personal information, with each one classified', 'Include IT/MSP, cloud email and storage, payroll, marketing and analytics vendors. Classification drives which contract terms apply and whether a disclosure is a sale or sharing.', null, ['vendor_mgmt', 'data_inventory']],
        ['Contracts', '§7051', 'Service provider and contractor contracts contain the required terms', 'Terms include: specified business purpose; prohibition on selling/sharing or using the data outside the contract; CCPA compliance and same level of privacy protection; notice if it can no longer comply; business right to take reasonable steps to stop unauthorized use; flow-down to subcontractors. Evidence: DPA or contract addendum for each vendor.', null, ['vendor_contracts']],
        ['Contracts', '§7053', 'Contracts with third parties to which personal information is sold or shared contain the required terms', 'Limited, specified purposes; third party complies with the CCPA and honors opt-outs forwarded to it; business may take steps to stop unauthorized use. Mark N/A if no sale or sharing.', null, ['vendor_contracts']],

        // ---- Data minimization & retention ---------------------------------------------
        ['Data minimization & retention', '§7002', 'Collection, use, retention and sharing of personal information is reasonably necessary and proportionate to the disclosed purposes', 'Review forms and systems for fields that are not needed (1798.100(c)); §7002 sets the reasonable-expectations and compatible-purpose tests. Evidence: data map with a purpose for each category.', null, ['data_inventory']],
        ['Data minimization & retention', '1798.100(a)(3)', 'A retention period (or the criteria used to set it) is defined and disclosed for each category of personal and sensitive information', 'Data is not kept longer than reasonably necessary for the disclosed purpose. Evidence: retention schedule and the matching privacy policy section.', null, ['data_retention_disposal', 'gov_privacy_notice']],
        ['Data minimization & retention', '1798.100(c)', 'Retention schedule is enforced: data past its retention period is securely deleted, including in email, file shares, SaaS apps and backups', 'Evidence: retention policies configured in Microsoft 365 or other systems, disposal logs, and certificates of destruction for retired media.', null, ['data_retention_disposal', 'media_sanitization']],

        // ---- Reasonable security --------------------------------------------------------
        ['Reasonable security', '1798.81.5', 'Reasonable security procedures and practices appropriate to the nature of the information are implemented and maintained', '1798.100(e) imposes the same duty under the CCPA. Evidence: written information security program, risk assessment, and control assessment (this tool\'s MSP Baseline or CIS IG1 results).', null, ['gov_policy', 'gov_risk_assessment']],
        ['Reasonable security', '1798.150', 'Personal information covered by the private right of action (e.g. name plus SSN, driver\'s license, financial account, medical or health insurance data, account login credentials) is encrypted or redacted', 'Breach of unencrypted and unredacted data caused by a failure to maintain reasonable security allows statutory damages of $107–$799 per consumer per incident (CPI-adjusted 2025). Evidence: BitLocker/FileVault reports, encryption of databases, backups and email.', null, ['data_encrypt_rest', 'ep_encryption', 'net_encrypt_transit']],
        ['Reasonable security', '1798.82', 'Breach notification procedure notifies affected California residents within 30 calendar days of discovery, and the Attorney General within 15 days of that notice if more than 500 residents are affected', 'SB 446 deadlines apply from Jan. 1, 2026 (delay allowed for law enforcement needs or to determine scope). Notices use the required "Notice of Data Breach" headings. Evidence: IR plan section and notice template.', null, ['ir_reporting', 'ir_plan']],

        // ---- Risk assessments -----------------------------------------------------------
        ['Risk assessments', '§7150', 'Processing that requires a risk assessment is identified', 'Triggers: selling or sharing personal information; processing sensitive personal information; using ADMT for a significant decision; automated profiling of employees, applicants, contractors or students, or based on presence in a sensitive location; processing to train ADMT for significant decisions or biometric/identity technologies. Evidence: list of in-scope processing activities.', null, ['gov_risk_assessment', 'data_inventory']],
        ['Risk assessments', '§7152', 'Each risk assessment report documents the purpose, categories of data, operational elements, benefits, negative impacts to consumers, safeguards, the decision whether to proceed, and contributors and approvers', 'Processing must not go ahead where risks to consumers\' privacy outweigh the benefits. Evidence: completed risk assessment report per activity.', null, ['gov_risk_assessment', 'gov_risk_treatment']],
        ['Risk assessments', '§7155', 'Risk assessments are done before starting new in-scope processing, by Dec. 31, 2027 for processing ongoing before 2026, reviewed at least every 3 years, and updated within 45 days of a material change', 'Retain reports for as long as the processing continues or five years after completion, whichever is later.', null, ['gov_risk_assessment', 'gov_review']],
        ['Risk assessments', '§7157', 'Risk assessment information and an executive attestation are submitted to the CPPA: first submission due Apr. 1, 2028 (covering 2026–2027), then annually by Apr. 1', 'Submission includes the period covered, number of assessments, categories of data, and an attestation signed under penalty of perjury by a member of executive management. Unabridged reports must be produced to the CPPA or AG on request.', null, ['gov_risk_assessment', 'gov_legal']],

        // ---- Cybersecurity audit --------------------------------------------------------
        ['Cybersecurity audit', '§7120', 'Cybersecurity audit applicability determined: processing presents significant risk to consumers\' security', 'Significant risk = 50%+ of revenue from selling or sharing personal information, OR revenue above the 1798.140(d)(1)(A) threshold AND in the prior year processed personal information of 250,000+ consumers/households or sensitive personal information of 50,000+ consumers. Mark the rest of this section N/A if not met.', null, ['gov_legal']],
        ['Cybersecurity audit', '§7121', 'First audit completed and certified by the deadline for the business\'s revenue tier, then annually', 'Over $100M revenue: Apr. 1, 2028 (covering 2027). $50M–$100M: Apr. 1, 2029 (covering 2028). Under $50M: Apr. 1, 2030 (covering 2029). After that, each Apr. 1 for the prior calendar year.', null, ['gov_review', 'gov_legal']],
        ['Cybersecurity audit', '§7122', 'Audit is performed by a qualified, objective, independent auditor (internal or external) using a recognized professional audit framework', 'An internal auditor must report to executive management with no direct responsibility for the cybersecurity program. The MSP that runs the program cannot audit its own work. Audit documents are retained at least five years.', null, ['gov_review']],
        ['Cybersecurity audit', '§7123(b)(2)(A)', 'Authentication, including phishing-resistant multi-factor authentication and strong, unique passwords or passphrases', 'Evidence: Conditional Access / MFA enforcement reports, password policy and password manager deployment.', null, ['iam_mfa', 'iam_passwords', 'iam_mfa_admin']],
        ['Cybersecurity audit', '§7123(b)(2)(B)', 'Encryption of personal information at rest and in transit', null, null, ['data_encrypt_rest', 'net_encrypt_transit', 'ep_encryption']],
        ['Cybersecurity audit', '§7123(b)(2)(C)', 'Account management and access controls (least privilege, separate privileged accounts, access reviews, prompt removal)', null, null, ['iam_least_privilege', 'iam_privileged', 'iam_accounts', 'iam_offboarding']],
        ['Cybersecurity audit', '§7123(b)(2)(D)', 'Inventory and management of personal information and of the information systems, hardware and software that process it', null, null, ['data_inventory', 'asset_hw_inventory', 'asset_sw_inventory']],
        ['Cybersecurity audit', '§7123(b)(2)(E)', 'Secure configuration of hardware and software, including software updates and patching', null, 'os_supported', ['cfg_baseline', 'vuln_patch_os', 'vuln_patch_apps']],
        ['Cybersecurity audit', '§7123(b)(2)(F)', 'Internal and external vulnerability scans, penetration testing, and vulnerability disclosure and reporting', null, null, ['vuln_scan', 'vuln_pentest', 'vuln_remediation']],
        ['Cybersecurity audit', '§7123(b)(2)(G)', 'Audit-log management, including centralized storage, retention and monitoring of logs', null, null, ['log_collect', 'log_retention', 'log_review']],
        ['Cybersecurity audit', '§7123(b)(2)(H)', 'Network monitoring and defenses, including bot detection and intrusion detection/prevention', null, null, ['net_ids', 'net_firewall']],
        ['Cybersecurity audit', '§7123(b)(2)(I)', 'Antivirus and antimalware protections', null, null, ['ep_malware', 'ep_edr']],
        ['Cybersecurity audit', '§7123(b)(2)(J)', 'Segmentation of information systems', null, null, ['net_segmentation']],
        ['Cybersecurity audit', '§7123(b)(2)(K)', 'Limitation and control of ports, services and protocols', null, null, ['cfg_ports_services']],
        ['Cybersecurity audit', '§7123(b)(2)(L)', 'Cybersecurity awareness: staying current on threats and communicating them to personnel', null, null, ['awareness_training', 'awareness_phishing']],
        ['Cybersecurity audit', '§7123(b)(2)(M)', 'Cybersecurity education and training at onboarding, at least annually, and after incidents', null, null, ['awareness_training']],
        ['Cybersecurity audit', '§7123(b)(2)(N)', 'Secure development and coding practices, including code review and testing', 'Mark N/A if the business does not develop software.', null, ['dev_secure']],
        ['Cybersecurity audit', '§7123(b)(2)(O)', 'Oversight of service providers, contractors and third parties', null, null, ['vendor_mgmt', 'vendor_contracts']],
        ['Cybersecurity audit', '§7123(b)(2)(P)', 'Retention schedules and secure disposal of personal information', null, null, ['data_retention_disposal', 'media_sanitization']],
        ['Cybersecurity audit', '§7123(b)(2)(Q)', 'Security incident response management, including a tested incident response plan', null, null, ['ir_plan', 'ir_test']],
        ['Cybersecurity audit', '§7123(b)(2)(R)', 'Business-continuity and disaster-recovery plans, including data recovery and backups', null, null, ['bc_plan', 'data_backup', 'data_restore_test']],
        ['Cybersecurity audit', '§7124', 'Annual certification of completion is submitted to the CPPA by April 1, signed by a member of executive management responsible for the audit', 'Evidence: copy of the submitted certification and the audit report (report must address each applicable §7123 component, gaps found and remediation plans).', null, ['gov_review', 'gov_risk_treatment']],

        // ---- ADMT -----------------------------------------------------------------------
        ['ADMT', '§7200', 'Use of automated decisionmaking technology (ADMT) for significant decisions is identified; compliance required by Jan. 1, 2027 (before first use for later deployments)', 'Significant decisions are those affecting financial or lending services, housing, education, employment or independent contracting, or healthcare. Include AI hiring/screening tools. Mark this section N/A if none.', null, ['gov_legal', 'gov_risk_assessment']],
        ['ADMT', '§7220', 'A pre-use notice is given before ADMT is used for a significant decision', 'Explains the specific purpose, the right to opt out (or the human-appeal alternative), the right to access ADMT information, and how the ADMT output is used in the decision.', null, ['gov_privacy_notice']],
        ['ADMT', '§7221', 'Consumers can opt out of ADMT for significant decisions, or an allowed exception (such as appeal to a qualified human reviewer who can overturn the decision) is in place', 'Evidence: opt-out method, appeal procedure and records of handled requests.', null, ['gov_privacy_notice']],
        ['ADMT', '§7222', 'Requests to access ADMT information are answered with the purpose, the logic used, and how the output affected the decision about the consumer', null, null, ['gov_privacy_notice']],
    ],
];
