<?php
/**
 * CMMC Level 2 — the 110 security requirements of NIST SP 800-171 Rev 2, as assessed under
 * 32 CFR 170.16/170.17. Titles quote NIST SP 800-171 r2 (public domain). Guidance summarizes
 * NIST SP 800-171A objectives and gives the DoD Assessment Methodology v1.2.1 (SPRS) point value.
 * POA&M eligibility follows 32 CFR 170.21(a)(2): only 1-point requirements (plus 3.13.11 when
 * encryption is used but not FIPS-validated), and never 3.1.20, 3.1.22, 3.10.3, 3.10.4, 3.10.5 or 3.12.4.
 */
return [
    'slug' => 'cmmc-l2',
    'name' => 'CMMC Level 2 (NIST SP 800-171 Rev 2)',
    'description' => 'Applies to defense contractors and subcontractors that process, store or transmit Controlled Unclassified Information (CUI). Covers all 110 security requirements of NIST SP 800-171 Rev 2, the same list DFARS 252.204-7012 already requires. Final status requires all 110 MET; Conditional status requires a score of at least 88 of 110 (SPRS-style, DoD Assessment Methodology) with only eligible 1-point items on a POA&M, closed out within 180 days. Status is by self-assessment or C3PAO certification (as the contract specifies) every 3 years, plus an annual affirmation in SPRS by a senior official. CMMC phase-in began Nov 10, 2025; Phase 2 (Nov 10, 2026) makes Level 2 C3PAO certification a condition of award where the solicitation requires it. Based on NIST SP 800-171 r2 (Feb 2020), SP 800-171A (June 2018) and 32 CFR Part 170. This is a summary for tracking an assessment, not legal advice.',
    'controls' => [
        // 3.1 Access Control
        ['Access Control (AC)', 'AC.L2-3.1.1', 'Limit system access to authorized users, processes acting on behalf of authorized users, and devices (including other systems).',
            'Objectives: authorized users, processes and devices are identified and access is limited to them. Evidence: access control policy, user/service account and device lists, offboarding records. SPRS: 5 pts; cannot be on a POA&M.',
            null, ['iam_accounts', 'iam_offboarding', 'asset_hw_inventory']],
        ['Access Control (AC)', 'AC.L2-3.1.2', 'Limit system access to the types of transactions and functions that authorized users are permitted to execute.',
            'Objectives: the transactions and functions each user may perform are defined and enforced. Evidence: role/group definitions, permission reports, file-share ACLs. SPRS: 5 pts; cannot be on a POA&M.',
            null, ['iam_least_privilege']],
        ['Access Control (AC)', 'AC.L2-3.1.3', 'Control the flow of CUI in accordance with approved authorizations.',
            'Objectives: information flow policies are defined and CUI flow is controlled by mechanisms such as firewalls, DLP or sensitivity labels. Evidence: CUI data flow diagram, firewall/DLP rules. SPRS: 1 pt; POA&M allowed.',
            null, ['data_inventory', 'data_dlp', 'net_firewall']],
        ['Access Control (AC)', 'AC.L2-3.1.4', 'Separate the duties of individuals to reduce the risk of malevolent activity without collusion.',
            'Objectives: duties requiring separation are defined and assigned to different people with matching access. Evidence: separation of duties matrix, role assignments (e.g. admins cannot approve their own changes or review their own logs). SPRS: 1 pt; POA&M allowed.',
            null, ['gov_roles', 'iam_least_privilege']],
        ['Access Control (AC)', 'AC.L2-3.1.5', 'Employ the principle of least privilege, including for specific security functions and privileged accounts.',
            'Objectives: privileged accounts and security functions are identified and access is granted by least privilege. Evidence: admin group membership report, privileged account list, access reviews. SPRS: 3 pts; cannot be on a POA&M.',
            null, ['iam_least_privilege', 'iam_privileged', 'iam_access_review']],
        ['Access Control (AC)', 'AC.L2-3.1.6', 'Use non-privileged accounts or roles when accessing nonsecurity functions.',
            'Objectives: admins use a standard account for email, web and daily work and a separate account only for admin tasks. Evidence: separate admin account list, policy, sign-in logs. SPRS: 1 pt; POA&M allowed.',
            null, ['iam_privileged']],
        ['Access Control (AC)', 'AC.L2-3.1.7', 'Prevent non-privileged users from executing privileged functions and capture the execution of such functions in audit logs.',
            'Objectives: privileged functions are defined, blocked for non-privileged users, and their execution is logged. Evidence: local admin removal report, UAC/PAM settings, audit log of privileged actions. SPRS: 1 pt; POA&M allowed.',
            null, ['iam_privileged', 'log_collect']],
        ['Access Control (AC)', 'AC.L2-3.1.8', 'Limit unsuccessful logon attempts.',
            'Objectives: a maximum number of failed logons is defined and enforced by lockout or delay. Evidence: account lockout GPO/Intune/Entra Smart Lockout settings. SPRS: 1 pt; POA&M allowed.',
            null, ['iam_lockout']],
        ['Access Control (AC)', 'AC.L2-3.1.9', 'Provide privacy and security notices consistent with applicable CUI rules.',
            'Objectives: required notices are identified and a logon banner or notice is displayed. Evidence: screenshot of logon banner on workstations, VPN and web portals. SPRS: 1 pt; POA&M allowed.',
            null, ['gov_legal']],
        ['Access Control (AC)', 'AC.L2-3.1.10', 'Use session lock with pattern-hiding displays to prevent access and viewing of data after a period of inactivity.',
            'Objectives: an inactivity period is defined, sessions lock after it and the screen is hidden. Evidence: screen lock GPO/Intune policy (e.g. 15 minutes). SPRS: 1 pt; POA&M allowed.',
            null, ['iam_session']],
        ['Access Control (AC)', 'AC.L2-3.1.11', 'Terminate (automatically) a user session after a defined condition.',
            'Objectives: conditions requiring session termination are defined and sessions end automatically when met. Evidence: RDP/VPN/web app idle disconnect settings, Entra sign-in frequency policy. SPRS: 1 pt; POA&M allowed.',
            null, ['iam_session']],
        ['Access Control (AC)', 'AC.L2-3.1.12', 'Monitor and control remote access sessions.',
            'Objectives: permitted remote access methods are identified, controlled and monitored. Evidence: VPN/remote tool configuration, remote access logs and alerting. SPRS: 5 pts; cannot be on a POA&M.',
            null, ['net_remote_access', 'log_review']],
        ['Access Control (AC)', 'AC.L2-3.1.13', 'Employ cryptographic mechanisms to protect the confidentiality of remote access sessions.',
            'Objectives: remote sessions are encrypted with approved cryptography. Evidence: VPN/RDP gateway crypto settings, FIPS mode configuration. SPRS: 5 pts; cannot be on a POA&M.',
            null, ['net_remote_access', 'net_encrypt_transit']],
        ['Access Control (AC)', 'AC.L2-3.1.14', 'Route remote access via managed access control points.',
            'Objectives: managed access control points are identified and all remote access goes through them. Evidence: network diagram, firewall/VPN configuration showing no direct RDP or other bypass. SPRS: 1 pt; POA&M allowed.',
            null, ['net_remote_access', 'net_firewall']],
        ['Access Control (AC)', 'AC.L2-3.1.15', 'Authorize remote execution of privileged commands and remote access to security-relevant information.',
            'Objectives: privileged remote commands and security information accessible remotely are identified and authorized. Evidence: remote admin policy, RMM/remote tool role permissions. SPRS: 1 pt; POA&M allowed.',
            null, ['net_remote_access', 'iam_privileged']],
        ['Access Control (AC)', 'AC.L2-3.1.16', 'Authorize wireless access prior to allowing such connections.',
            'Objectives: wireless access points are identified and connections are authorized before use. Evidence: wireless policy, WLAN controller configuration, list of authorized SSIDs. SPRS: 5 pts; cannot be on a POA&M.',
            null, ['net_wireless']],
        ['Access Control (AC)', 'AC.L2-3.1.17', 'Protect wireless access using authentication and encryption.',
            'Objectives: wireless access requires authentication and is encrypted. Evidence: WPA2/WPA3-Enterprise (802.1X) configuration screenshots. SPRS: 5 pts; cannot be on a POA&M.',
            null, ['net_wireless', 'net_encrypt_transit']],
        ['Access Control (AC)', 'AC.L2-3.1.18', 'Control connection of mobile devices.',
            'Objectives: mobile devices that process CUI are identified and their connection is authorized and controlled. Evidence: MDM enrollment and compliance policies, Conditional Access rules. SPRS: 5 pts; cannot be on a POA&M.',
            null, ['ep_mdm']],
        ['Access Control (AC)', 'AC.L2-3.1.19', 'Encrypt CUI on mobile devices and mobile computing platforms.',
            'Objectives: mobile devices and laptops holding CUI are encrypted. Evidence: BitLocker/FileVault/MDM encryption compliance report. SPRS: 3 pts; cannot be on a POA&M.',
            null, ['ep_encryption', 'ep_mdm', 'data_encrypt_rest']],
        ['Access Control (AC)', 'AC.L2-3.1.20', 'Verify and control/limit connections to and use of external systems.',
            'Objectives: external systems are identified and their connection and use is verified, controlled and limited. Evidence: BYOD/acceptable use policy, Conditional Access or MDM rules, approved external service list. SPRS: 1 pt; cannot be on a POA&M (32 CFR 170.21 excluded requirement).',
            null, ['net_remote_access', 'ep_mdm', 'hr_agreements']],
        ['Access Control (AC)', 'AC.L2-3.1.21', 'Limit use of portable storage devices on external systems.',
            'Objectives: use of company portable storage on external systems is defined and limited. Evidence: removable media policy, USB control settings. SPRS: 1 pt; POA&M allowed.',
            null, ['media_protection']],
        ['Access Control (AC)', 'AC.L2-3.1.22', 'Control CUI posted or processed on publicly accessible systems.',
            'Objectives: authorized posters are identified and trained, and content is reviewed before and after posting so CUI is not made public. Evidence: authorized poster list, review procedure and records. SPRS: 1 pt; cannot be on a POA&M (32 CFR 170.21 excluded requirement).',
            null, ['gov_policy', 'data_inventory']],
        // 3.2 Awareness and Training
        ['Awareness and Training (AT)', 'AT.L2-3.2.1', 'Ensure that managers, system administrators, and users of organizational systems are made aware of the security risks associated with their activities and of the applicable policies, standards, and procedures related to the security of those systems.',
            'Objectives: security risks and applicable policies are identified and all users receive awareness training. Evidence: training content, completion records. SPRS: 5 pts; cannot be on a POA&M.',
            null, ['awareness_training', 'awareness_phishing']],
        ['Awareness and Training (AT)', 'AT.L2-3.2.2', 'Ensure that personnel are trained to carry out their assigned information security-related duties and responsibilities.',
            'Objectives: security-related duties are defined and people in those roles get role-based training. Evidence: role-based training plan, admin/IT staff training records or certifications. SPRS: 5 pts; cannot be on a POA&M.',
            null, ['awareness_training', 'gov_roles']],
        ['Awareness and Training (AT)', 'AT.L2-3.2.3', 'Provide security awareness training on recognizing and reporting potential indicators of insider threat.',
            'Objectives: insider threat indicators are identified and training on recognizing and reporting them is delivered. Evidence: insider threat training module and completion records. SPRS: 1 pt; POA&M allowed.',
            null, ['awareness_training']],
        // 3.3 Audit and Accountability
        ['Audit and Accountability (AU)', 'AU.L2-3.3.1', 'Create and retain system audit logs and records to the extent needed to enable the monitoring, analysis, investigation, and reporting of unlawful or unauthorized system activity.',
            'Objectives: required audit events and content are defined, logs are created and retained for a defined period. Evidence: audit policy/GPO, log source list, SIEM or M365 audit retention settings. SPRS: 5 pts; cannot be on a POA&M.',
            null, ['log_collect', 'log_retention']],
        ['Audit and Accountability (AU)', 'AU.L2-3.3.2', 'Ensure that the actions of individual system users can be uniquely traced to those users, so they can be held accountable for their actions.',
            'Objectives: log records contain enough detail (user, time, event) to trace actions to individuals. Evidence: sample log entries, no shared accounts. SPRS: 3 pts; cannot be on a POA&M.',
            null, ['log_collect', 'iam_accounts']],
        ['Audit and Accountability (AU)', 'AU.L2-3.3.3', 'Review and update logged events.',
            'Objectives: a process for periodically reviewing and updating the list of logged events exists and is followed. Evidence: dated review record of audit event list. SPRS: 1 pt; POA&M allowed.',
            null, ['log_collect', 'gov_review']],
        ['Audit and Accountability (AU)', 'AU.L2-3.3.4', 'Alert in the event of an audit logging process failure.',
            'Objectives: personnel to alert and the failure types are defined and alerts fire when logging fails. Evidence: SIEM/log source health alert configuration. SPRS: 1 pt; POA&M allowed.',
            null, ['log_review', 'log_collect']],
        ['Audit and Accountability (AU)', 'AU.L2-3.3.5', 'Correlate audit record review, analysis, and reporting processes for investigation and response to indications of unlawful, unauthorized, suspicious, or unusual activity.',
            'Objectives: log review, analysis and reporting processes are defined and correlated across sources. Evidence: SIEM/SOC correlation rules, review procedure, sample investigations. SPRS: 5 pts; cannot be on a POA&M.',
            null, ['log_review']],
        ['Audit and Accountability (AU)', 'AU.L2-3.3.6', 'Provide audit record reduction and report generation to support on-demand analysis and reporting.',
            'Objectives: log reduction and on-demand reporting capability is provided. Evidence: SIEM search/report screenshots, saved queries. SPRS: 1 pt; POA&M allowed.',
            null, ['log_review']],
        ['Audit and Accountability (AU)', 'AU.L2-3.3.7', 'Provide a system capability that compares and synchronizes internal system clocks with an authoritative source to generate time stamps for audit records.',
            'Objectives: an authoritative time source is defined and systems synchronize to it. Evidence: NTP configuration on domain controllers, firewalls and servers. SPRS: 1 pt; POA&M allowed.',
            null, ['log_time_sync']],
        ['Audit and Accountability (AU)', 'AU.L2-3.3.8', 'Protect audit information and audit logging tools from unauthorized access, modification, and deletion.',
            'Objectives: logs and logging tools are protected from unauthorized access, change and deletion. Evidence: SIEM access roles, immutable/forwarded log storage settings. SPRS: 1 pt; POA&M allowed.',
            null, ['log_protect']],
        ['Audit and Accountability (AU)', 'AU.L2-3.3.9', 'Limit management of audit logging functionality to a subset of privileged users.',
            'Objectives: the privileged users allowed to manage logging are defined and limited. Evidence: list of logging admins, SIEM/audit policy permission settings. SPRS: 1 pt; POA&M allowed.',
            null, ['log_protect', 'iam_privileged']],
        // 3.4 Configuration Management
        ['Configuration Management (CM)', 'CM.L2-3.4.1', 'Establish and maintain baseline configurations and inventories of organizational systems (including hardware, software, firmware, and documentation) throughout the respective system development life cycles.',
            'Objectives: baseline configurations and a hardware/software/firmware inventory are established, documented and kept current. Evidence: baseline documents (e.g. CIS/STIG-based), RMM asset inventory. SPRS: 5 pts; cannot be on a POA&M.',
            null, ['cfg_baseline', 'asset_hw_inventory', 'asset_sw_inventory']],
        ['Configuration Management (CM)', 'CM.L2-3.4.2', 'Establish and enforce security configuration settings for information technology products employed in organizational systems.',
            'Objectives: security settings are defined and enforced for each product type. Evidence: GPO/Intune configuration profiles, compliance reports. SPRS: 5 pts; cannot be on a POA&M.',
            null, ['cfg_baseline', 'cloud_config']],
        ['Configuration Management (CM)', 'CM.L2-3.4.3', 'Track, review, approve or disapprove, and log changes to organizational systems.',
            'Objectives: changes are tracked, reviewed, approved or rejected, and logged. Evidence: change management procedure, change tickets with approvals. SPRS: 1 pt; POA&M allowed.',
            null, ['cfg_change']],
        ['Configuration Management (CM)', 'CM.L2-3.4.4', 'Analyze the security impact of changes prior to implementation.',
            'Objectives: security impact is analyzed before a change is made. Evidence: change tickets with a security impact section. SPRS: 1 pt; POA&M allowed.',
            null, ['cfg_change']],
        ['Configuration Management (CM)', 'CM.L2-3.4.5', 'Define, document, approve, and enforce physical and logical access restrictions associated with changes to organizational systems.',
            'Objectives: who can make changes (physically and logically) is defined, approved and enforced. Evidence: list of change-authorized staff, admin rights and server room access restrictions. SPRS: 5 pts; cannot be on a POA&M.',
            null, ['cfg_change', 'iam_privileged']],
        ['Configuration Management (CM)', 'CM.L2-3.4.6', 'Employ the principle of least functionality by configuring organizational systems to provide only essential capabilities.',
            'Objectives: essential capabilities are defined and systems are configured to provide only those. Evidence: hardening baselines, removed roles/features, software standards. SPRS: 5 pts; cannot be on a POA&M.',
            null, ['cfg_ports_services', 'cfg_baseline']],
        ['Configuration Management (CM)', 'CM.L2-3.4.7', 'Restrict, disable, or prevent the use of nonessential programs, functions, ports, protocols, and services.',
            'Objectives: essential programs, ports, protocols and services are defined and nonessential ones are restricted or disabled. Evidence: port/service scans, firewall rules, disabled services list. SPRS: 5 pts; cannot be on a POA&M.',
            null, ['cfg_ports_services', 'asset_unauth_sw']],
        ['Configuration Management (CM)', 'CM.L2-3.4.8', 'Apply deny-by-exception (blacklisting) policy to prevent the use of unauthorized software or deny-all, permit-by-exception (whitelisting) policy to allow the execution of authorized software.',
            'Objectives: the organization chooses blocklisting or allowlisting, defines the list, and enforces it. Evidence: application control policy (e.g. WDAC, AppLocker, ThreatLocker), software approval list. SPRS: 5 pts; cannot be on a POA&M.',
            null, ['asset_unauth_sw', 'asset_sw_inventory']],
        ['Configuration Management (CM)', 'CM.L2-3.4.9', 'Control and monitor user-installed software.',
            'Objectives: a policy for user-installed software exists, installation is controlled and monitored. Evidence: software install policy, local admin removal, RMM software change reports. SPRS: 1 pt; POA&M allowed.',
            null, ['asset_unauth_sw', 'asset_sw_inventory']],
        // 3.5 Identification and Authentication
        ['Identification and Authentication (IA)', 'IA.L2-3.5.1', 'Identify system users, processes acting on behalf of users, and devices.',
            'Objectives: users, processes and devices have unique identifiers. Evidence: user/service account export, device inventory. SPRS: 5 pts; cannot be on a POA&M.',
            null, ['iam_accounts', 'asset_hw_inventory']],
        ['Identification and Authentication (IA)', 'IA.L2-3.5.2', 'Authenticate (or verify) the identities of users, processes, or devices, as a prerequisite to allowing access to organizational systems.',
            'Objectives: users, processes and devices are authenticated before access; default credentials are changed. Evidence: authentication settings, proof default passwords changed. SPRS: 5 pts; cannot be on a POA&M.',
            null, ['iam_passwords', 'iam_accounts']],
        ['Identification and Authentication (IA)', 'IA.L2-3.5.3', 'Use multifactor authentication for local and network access to privileged accounts and for network access to non-privileged accounts.',
            'Objectives: privileged accounts use MFA for local and network access and all users use MFA for network access. Evidence: Conditional Access/MFA policies, MFA registration report, MFA on admin and VPN logons. SPRS: 5 pts, or 3 if MFA covers remote and privileged access but not all general users; cannot be on a POA&M.',
            null, ['iam_mfa', 'iam_mfa_remote', 'iam_mfa_admin']],
        ['Identification and Authentication (IA)', 'IA.L2-3.5.4', 'Employ replay-resistant authentication mechanisms for network access to privileged and non-privileged accounts.',
            'Objectives: network authentication resists replay (e.g. Kerberos, TLS, time-based or challenge-response MFA). Evidence: NTLMv1/legacy auth disabled, authentication protocol settings. SPRS: 1 pt; POA&M allowed.',
            null, ['iam_mfa', 'cloud_config']],
        ['Identification and Authentication (IA)', 'IA.L2-3.5.5', 'Prevent reuse of identifiers for a defined period.',
            'Objectives: a period is defined during which user and device identifiers are not reused. Evidence: account naming/lifecycle procedure. SPRS: 1 pt; POA&M allowed.',
            null, ['iam_accounts']],
        ['Identification and Authentication (IA)', 'IA.L2-3.5.6', 'Disable identifiers after a defined period of inactivity.',
            'Objectives: an inactivity period is defined and inactive accounts are disabled after it. Evidence: stale account report, automated disable script or Entra/AD policy. SPRS: 1 pt; POA&M allowed.',
            null, ['iam_accounts', 'iam_access_review']],
        ['Identification and Authentication (IA)', 'IA.L2-3.5.7', 'Enforce a minimum password complexity and change of characters when new passwords are created.',
            'Objectives: password complexity and character-change requirements are defined and enforced. Evidence: password policy GPO/Entra settings. SPRS: 1 pt; POA&M allowed.',
            null, ['iam_passwords']],
        ['Identification and Authentication (IA)', 'IA.L2-3.5.8', 'Prohibit password reuse for a specified number of generations.',
            'Objectives: the number of generations is specified and reuse is blocked. Evidence: password history setting. SPRS: 1 pt; POA&M allowed.',
            null, ['iam_passwords']],
        ['Identification and Authentication (IA)', 'IA.L2-3.5.9', 'Allow temporary password use for system logons with an immediate change to a permanent password.',
            'Objectives: temporary passwords require an immediate change at first logon. Evidence: "change password at next logon" setting in account creation procedure. SPRS: 1 pt; POA&M allowed.',
            null, ['iam_passwords', 'iam_accounts']],
        ['Identification and Authentication (IA)', 'IA.L2-3.5.10', 'Store and transmit only cryptographically-protected passwords.',
            'Objectives: passwords are stored hashed/encrypted and transmitted only over encrypted channels. Evidence: no plaintext password stores, password manager in use, protocol settings. SPRS: 5 pts; cannot be on a POA&M.',
            null, ['iam_passwords', 'net_encrypt_transit']],
        ['Identification and Authentication (IA)', 'IA.L2-3.5.11', 'Obscure feedback of authentication information.',
            'Objectives: authentication input is masked during entry. Evidence: screenshots of masked password fields on logon screens. SPRS: 1 pt; POA&M allowed.',
            null, ['iam_passwords']],
        // 3.6 Incident Response
        ['Incident Response (IR)', 'IR.L2-3.6.1', 'Establish an operational incident-handling capability for organizational systems that includes preparation, detection, analysis, containment, recovery, and user response activities.',
            'Objectives: an incident handling capability covering preparation through recovery and user response is established. Evidence: incident response plan, contact lists, tools and SOC/MDR arrangements. SPRS: 5 pts; cannot be on a POA&M.',
            null, ['ir_plan', 'log_review']],
        ['Incident Response (IR)', 'IR.L2-3.6.2', 'Track, document, and report incidents to designated officials and/or authorities both internal and external to the organization.',
            'Objectives: incidents are tracked, documented and reported to designated internal and external parties (including DoD within 72 hours under DFARS 252.204-7012). Evidence: incident log/tickets, reporting procedure, DIBNet access. SPRS: 5 pts; cannot be on a POA&M.',
            null, ['ir_reporting', 'ir_plan']],
        ['Incident Response (IR)', 'IR.L2-3.6.3', 'Test the organizational incident response capability.',
            'Objectives: incident response capability is tested on a defined schedule. Evidence: tabletop exercise report, after-action notes. SPRS: 1 pt; POA&M allowed.',
            null, ['ir_test']],
        // 3.7 Maintenance
        ['Maintenance (MA)', 'MA.L2-3.7.1', 'Perform maintenance on organizational systems.',
            'Objectives: system maintenance is performed as scheduled and as needed. Evidence: maintenance procedure, RMM maintenance/patch records. SPRS: 3 pts; cannot be on a POA&M.',
            null, ['vuln_patch_os', 'cfg_change']],
        ['Maintenance (MA)', 'MA.L2-3.7.2', 'Provide controls on the tools, techniques, mechanisms, and personnel used to conduct system maintenance.',
            'Objectives: maintenance tools, techniques, mechanisms and personnel are controlled. Evidence: approved maintenance tool list (RMM, remote tools), authorized maintenance personnel list. SPRS: 5 pts; cannot be on a POA&M.',
            null, ['net_remote_access', 'iam_privileged']],
        ['Maintenance (MA)', 'MA.L2-3.7.3', 'Ensure equipment removed for off-site maintenance is sanitized of any CUI.',
            'Objectives: equipment leaving for off-site repair is sanitized of CUI (or drives removed). Evidence: off-site repair procedure, sanitization records. SPRS: 1 pt; POA&M allowed.',
            null, ['media_sanitization']],
        ['Maintenance (MA)', 'MA.L2-3.7.4', 'Check media containing diagnostic and test programs for malicious code before the media are used in organizational systems.',
            'Objectives: diagnostic/test media are scanned for malware before use. Evidence: procedure requiring scans, AV removable media scan settings. SPRS: 3 pts; cannot be on a POA&M.',
            null, ['ep_malware', 'media_protection']],
        ['Maintenance (MA)', 'MA.L2-3.7.5', 'Require multifactor authentication to establish nonlocal maintenance sessions via external network connections and terminate such connections when nonlocal maintenance is complete.',
            'Objectives: remote maintenance sessions require MFA and are terminated when done. Evidence: MFA on RMM/remote tools and vendor access, session timeout settings. SPRS: 5 pts; cannot be on a POA&M.',
            null, ['iam_mfa_remote', 'iam_mfa_admin', 'net_remote_access']],
        ['Maintenance (MA)', 'MA.L2-3.7.6', 'Supervise the maintenance activities of maintenance personnel without required access authorization.',
            'Objectives: maintenance by people without access authorization (e.g. vendor techs) is supervised. Evidence: escort/supervision procedure, vendor session logs. SPRS: 1 pt; POA&M allowed.',
            null, ['phys_visitors', 'vendor_mgmt']],
        // 3.8 Media Protection
        ['Media Protection (MP)', 'MP.L2-3.8.1', 'Protect (i.e., physically control and securely store) system media containing CUI, both paper and digital.',
            'Objectives: paper and digital media holding CUI are physically controlled and securely stored. Evidence: media protection policy, locked storage, photos. SPRS: 3 pts; cannot be on a POA&M.',
            null, ['media_protection', 'phys_access']],
        ['Media Protection (MP)', 'MP.L2-3.8.2', 'Limit access to CUI on system media to authorized users.',
            'Objectives: access to CUI on media is limited to authorized users. Evidence: storage access lists, USB/removable media restrictions. SPRS: 3 pts; cannot be on a POA&M.',
            null, ['media_protection', 'iam_least_privilege']],
        ['Media Protection (MP)', 'MP.L2-3.8.3', 'Sanitize or destroy system media containing CUI before disposal or release for reuse.',
            'Objectives: media holding CUI are sanitized or destroyed before disposal or reuse. Evidence: sanitization procedure (NIST SP 800-88), wipe logs or certificates of destruction. SPRS: 5 pts; cannot be on a POA&M.',
            null, ['media_sanitization', 'data_retention_disposal']],
        ['Media Protection (MP)', 'MP.L2-3.8.4', 'Mark media with necessary CUI markings and distribution limitations.',
            'Objectives: media holding CUI are marked with CUI markings and distribution limits. Evidence: marking procedure, sample marked documents/drives, sensitivity labels. SPRS: 1 pt; POA&M allowed.',
            null, ['media_protection', 'data_inventory']],
        ['Media Protection (MP)', 'MP.L2-3.8.5', 'Control access to media containing CUI and maintain accountability for media during transport outside of controlled areas.',
            'Objectives: media in transport are access-controlled and accountability is maintained. Evidence: transport procedure, chain-of-custody log, encrypted/tracked shipping. SPRS: 1 pt; POA&M allowed.',
            null, ['media_protection']],
        ['Media Protection (MP)', 'MP.L2-3.8.6', 'Implement cryptographic mechanisms to protect the confidentiality of CUI stored on digital media during transport unless otherwise protected by alternative physical safeguards.',
            'Objectives: digital media carrying CUI in transport are encrypted unless otherwise physically protected. Evidence: encrypted USB/BitLocker To Go policy, laptop encryption report. SPRS: 1 pt; POA&M allowed.',
            null, ['media_protection', 'data_encrypt_rest', 'ep_encryption']],
        ['Media Protection (MP)', 'MP.L2-3.8.7', 'Control the use of removable media on system components.',
            'Objectives: use of removable media is controlled (allowed, restricted or blocked). Evidence: device control GPO/Intune/EDR policy. SPRS: 5 pts; cannot be on a POA&M.',
            null, ['media_protection']],
        ['Media Protection (MP)', 'MP.L2-3.8.8', 'Prohibit the use of portable storage devices when such devices have no identifiable owner.',
            'Objectives: portable storage without an identifiable owner is prohibited. Evidence: removable media policy, device control rules, approved device list. SPRS: 3 pts; cannot be on a POA&M.',
            null, ['media_protection']],
        ['Media Protection (MP)', 'MP.L2-3.8.9', 'Protect the confidentiality of backup CUI at storage locations.',
            'Objectives: backups containing CUI are protected (e.g. encrypted, access-restricted) where stored. Evidence: backup encryption settings, backup storage access controls. SPRS: 1 pt; POA&M allowed.',
            null, ['data_backup', 'data_encrypt_rest']],
        // 3.9 Personnel Security
        ['Personnel Security (PS)', 'PS.L2-3.9.1', 'Screen individuals prior to authorizing access to organizational systems containing CUI.',
            'Objectives: individuals are screened before being granted access to CUI systems. Evidence: screening/background check procedure and records. SPRS: 3 pts; cannot be on a POA&M.',
            null, ['hr_screening']],
        ['Personnel Security (PS)', 'PS.L2-3.9.2', 'Ensure that organizational systems containing CUI are protected during and after personnel actions such as terminations and transfers.',
            'Objectives: on termination or transfer, access is revoked or adjusted and credentials and equipment are recovered. Evidence: offboarding checklist, tickets showing timely disablement. SPRS: 5 pts; cannot be on a POA&M.',
            null, ['iam_offboarding', 'iam_access_review']],
        // 3.10 Physical Protection
        ['Physical Protection (PE)', 'PE.L2-3.10.1', 'Limit physical access to organizational systems, equipment, and the respective operating environments to authorized individuals.',
            'Objectives: authorized individuals are identified and physical access to systems and equipment is limited to them. Evidence: authorized access list, badge/key records, locked server room/rack. SPRS: 5 pts; cannot be on a POA&M.',
            null, ['phys_access']],
        ['Physical Protection (PE)', 'PE.L2-3.10.2', 'Protect and monitor the physical facility and support infrastructure for organizational systems.',
            'Objectives: the facility and support infrastructure are protected and monitored. Evidence: alarm system, cameras, monitoring records. SPRS: 5 pts; cannot be on a POA&M.',
            null, ['phys_access', 'phys_environment']],
        ['Physical Protection (PE)', 'PE.L2-3.10.3', 'Escort visitors and monitor visitor activity.',
            'Objectives: visitors are escorted and their activity monitored. Evidence: visitor/escort policy, sign-in log. SPRS: 1 pt; cannot be on a POA&M (32 CFR 170.21 excluded requirement).',
            null, ['phys_visitors']],
        ['Physical Protection (PE)', 'PE.L2-3.10.4', 'Maintain audit logs of physical access.',
            'Objectives: physical access logs are kept. Evidence: badge system logs or visitor/access logbook. SPRS: 1 pt; cannot be on a POA&M (32 CFR 170.21 excluded requirement).',
            null, ['phys_visitors', 'phys_access']],
        ['Physical Protection (PE)', 'PE.L2-3.10.5', 'Control and manage physical access devices.',
            'Objectives: keys, badges and combinations are identified, controlled and managed. Evidence: key/badge inventory, issuance and revocation records, combination change log. SPRS: 1 pt; cannot be on a POA&M (32 CFR 170.21 excluded requirement).',
            null, ['phys_access']],
        ['Physical Protection (PE)', 'PE.L2-3.10.6', 'Enforce safeguarding measures for CUI at alternate work sites.',
            'Objectives: safeguards for alternate work sites (e.g. home offices) are defined and enforced. Evidence: telework policy, signed telework agreements, technical controls for remote devices. SPRS: 1 pt; POA&M allowed.',
            null, ['hr_agreements', 'net_remote_access']],
        // 3.11 Risk Assessment
        ['Risk Assessment (RA)', 'RA.L2-3.11.1', 'Periodically assess the risk to organizational operations (including mission, functions, image, or reputation), organizational assets, and individuals, resulting from the operation of organizational systems and the associated processing, storage, or…',
            'Objectives: risk assessment frequency is defined and risk assessments are performed. Evidence: dated risk assessment report and risk register. SPRS: 3 pts; cannot be on a POA&M.',
            null, ['gov_risk_assessment']],
        ['Risk Assessment (RA)', 'RA.L2-3.11.2', 'Scan for vulnerabilities in organizational systems and applications periodically and when new vulnerabilities affecting those systems and applications are identified.',
            'Objectives: scan frequency is defined and systems and applications are scanned periodically and when new vulnerabilities emerge. Evidence: vulnerability scanner configuration and recent reports. SPRS: 5 pts; cannot be on a POA&M.',
            null, ['vuln_scan']],
        ['Risk Assessment (RA)', 'RA.L2-3.11.3', 'Remediate vulnerabilities in accordance with risk assessments.',
            'Objectives: vulnerabilities are remediated according to assessed risk. Evidence: remediation timelines by severity, tickets, rescan results. SPRS: 1 pt; POA&M allowed.',
            null, ['vuln_remediation', 'gov_risk_treatment']],
        // 3.12 Security Assessment
        ['Security Assessment (CA)', 'CA.L2-3.12.1', 'Periodically assess the security controls in organizational systems to determine if the controls are effective in their application.',
            'Objectives: assessment frequency is defined and controls are assessed for effectiveness. Evidence: dated self-assessment against all 110 requirements, assessment report. SPRS: 5 pts; cannot be on a POA&M.',
            null, ['gov_review']],
        ['Security Assessment (CA)', 'CA.L2-3.12.2', 'Develop and implement plans of action designed to correct deficiencies and reduce or eliminate vulnerabilities in organizational systems.',
            'Objectives: deficiencies are identified and plans of action to correct them are developed and implemented. Evidence: POA&M with owners, milestones and dates. SPRS: 3 pts; cannot be on a POA&M.',
            null, ['gov_risk_treatment', 'vuln_remediation']],
        ['Security Assessment (CA)', 'CA.L2-3.12.3', 'Monitor security controls on an ongoing basis to ensure the continued effectiveness of the controls.',
            'Objectives: security controls are monitored on an ongoing basis. Evidence: continuous monitoring plan, dashboards, periodic review records. SPRS: 5 pts; cannot be on a POA&M.',
            null, ['gov_review', 'log_review']],
        ['Security Assessment (CA)', 'CA.L2-3.12.4', 'Develop, document, and periodically update system security plans that describe system boundaries, system environments of operation, how security requirements are implemented, and the relationships with or connections to other systems.',
            'Objectives: an SSP describes the boundary, environment, how each requirement is implemented and connections to other systems, and is periodically updated. Evidence: current dated SSP, network diagram, CUI data flow. SPRS: no point value (without an SSP the assessment cannot proceed); never allowed on a POA&M.',
            null, ['gov_policy', 'data_inventory']],
        // 3.13 System and Communications Protection
        ['System and Communications Protection (SC)', 'SC.L2-3.13.1', 'Monitor, control, and protect communications (i.e., information transmitted or received by organizational systems) at the external boundaries and key internal boundaries of organizational systems.',
            'Objectives: external and key internal boundaries are defined and communications there are monitored, controlled and protected. Evidence: network diagram, firewall rule export, boundary logs. SPRS: 5 pts; cannot be on a POA&M.',
            'warranty', ['net_firewall', 'net_ids']],
        ['System and Communications Protection (SC)', 'SC.L2-3.13.2', 'Employ architectural designs, software development techniques, and systems engineering principles that promote effective information security within organizational systems.',
            'Objectives: security architecture, development and engineering principles are defined and applied. Evidence: architecture documentation, secure design standards, secure development practices if applicable. SPRS: 5 pts; cannot be on a POA&M.',
            null, ['dev_secure', 'net_segmentation']],
        ['System and Communications Protection (SC)', 'SC.L2-3.13.3', 'Separate user functionality from system management functionality.',
            'Objectives: user functions and system management functions are separated (e.g. separate admin interfaces, accounts or networks). Evidence: management VLAN, admin portals restricted, separate admin accounts. SPRS: 1 pt; POA&M allowed.',
            null, ['iam_privileged', 'net_segmentation']],
        ['System and Communications Protection (SC)', 'SC.L2-3.13.4', 'Prevent unauthorized and unintended information transfer via shared system resources.',
            'Objectives: information cannot leak through shared resources (memory, storage, shared folders). Evidence: OS configuration, shared resource permissions. SPRS: 1 pt; POA&M allowed.',
            null, ['cfg_baseline', 'iam_least_privilege']],
        ['System and Communications Protection (SC)', 'SC.L2-3.13.5', 'Implement subnetworks for publicly accessible system components that are physically or logically separated from internal networks.',
            'Objectives: publicly accessible components are identified and placed in physically or logically separate subnetworks. Evidence: DMZ/VLAN configuration, network diagram, zone firewall rules. SPRS: 5 pts; cannot be on a POA&M.',
            null, ['net_segmentation', 'net_firewall']],
        ['System and Communications Protection (SC)', 'SC.L2-3.13.6', 'Deny network communications traffic by default and allow network communications traffic by exception (i.e., deny all, permit by exception).',
            'Objectives: network traffic is denied by default and allowed only by exception, inbound and outbound. Evidence: firewall rule set ending in deny-all, documented exceptions. SPRS: 5 pts; cannot be on a POA&M.',
            null, ['net_firewall', 'cfg_ports_services']],
        ['System and Communications Protection (SC)', 'SC.L2-3.13.7', 'Prevent remote devices from simultaneously establishing non-remote connections with organizational systems and communicating via some other connection to resources in external networks (i.e., split tunneling).',
            'Objectives: split tunneling is disabled or controlled for remote devices. Evidence: VPN client configuration showing full tunnel. SPRS: 1 pt; POA&M allowed.',
            null, ['net_remote_access']],
        ['System and Communications Protection (SC)', 'SC.L2-3.13.8', 'Implement cryptographic mechanisms to prevent unauthorized disclosure of CUI during transmission unless otherwise protected by alternative physical safeguards.',
            'Objectives: CUI in transit is encrypted unless otherwise physically protected. Evidence: TLS/VPN configuration, email encryption settings. SPRS: 3 pts; cannot be on a POA&M.',
            null, ['net_encrypt_transit']],
        ['System and Communications Protection (SC)', 'SC.L2-3.13.9', 'Terminate network connections associated with communications sessions at the end of the sessions or after a defined period of inactivity.',
            'Objectives: an inactivity period is defined and network connections end after it or at session end. Evidence: VPN/firewall/RDP idle timeout settings. SPRS: 1 pt; POA&M allowed.',
            null, ['iam_session', 'net_remote_access']],
        ['System and Communications Protection (SC)', 'SC.L2-3.13.10', 'Establish and manage cryptographic keys for cryptography employed in organizational systems.',
            'Objectives: key management requirements are defined and keys are established and managed accordingly. Evidence: key management procedure, BitLocker key escrow, certificate inventory. SPRS: 1 pt; POA&M allowed.',
            null, ['data_encrypt_rest', 'net_encrypt_transit']],
        ['System and Communications Protection (SC)', 'SC.L2-3.13.11', 'Employ FIPS-validated cryptography when used to protect the confidentiality of CUI.',
            'Objectives: cryptography protecting CUI uses FIPS 140-validated modules. Evidence: CMVP certificate numbers for encryption products, FIPS mode settings. SPRS: 5 pts, or 3 if encryption is used but not FIPS-validated; only that partial case may be on a POA&M.',
            null, ['data_encrypt_rest', 'net_encrypt_transit', 'ep_encryption']],
        ['System and Communications Protection (SC)', 'SC.L2-3.13.12', 'Prohibit remote activation of collaborative computing devices and provide indication of devices in use to users present at the device.',
            'Objectives: remote activation of cameras/microphones is blocked (except where allowed) and users see when devices are in use. Evidence: conferencing device settings, camera/mic indicator lights. SPRS: 1 pt; POA&M allowed.',
            null, ['cfg_baseline']],
        ['System and Communications Protection (SC)', 'SC.L2-3.13.13', 'Control and monitor the use of mobile code.',
            'Objectives: acceptable mobile code (scripts, macros, Java) is defined and its use is controlled and monitored. Evidence: Office macro policy, browser script controls, PowerShell restrictions. SPRS: 1 pt; POA&M allowed.',
            null, ['browser_controls', 'asset_unauth_sw']],
        ['System and Communications Protection (SC)', 'SC.L2-3.13.14', 'Control and monitor the use of Voice over Internet Protocol (VoIP) technologies.',
            'Objectives: VoIP use is controlled and monitored. Evidence: VoIP policy, phone system admin controls, VoIP VLAN and logs. SPRS: 1 pt; POA&M allowed.',
            null, ['net_segmentation']],
        ['System and Communications Protection (SC)', 'SC.L2-3.13.15', 'Protect the authenticity of communications sessions.',
            'Objectives: session authenticity is protected (e.g. TLS with valid certificates, protection against session hijacking). Evidence: TLS configuration, certificate management. SPRS: 5 pts; cannot be on a POA&M.',
            null, ['net_encrypt_transit']],
        ['System and Communications Protection (SC)', 'SC.L2-3.13.16', 'Protect the confidentiality of CUI at rest.',
            'Objectives: CUI at rest is protected, typically by encryption. Evidence: full-disk encryption report, encrypted file shares/cloud storage settings. SPRS: 1 pt; POA&M allowed.',
            null, ['data_encrypt_rest', 'ep_encryption']],
        // 3.14 System and Information Integrity
        ['System and Information Integrity (SI)', 'SI.L2-3.14.1', 'Identify, report, and correct system flaws in a timely manner.',
            'Objectives: time frames are defined and system flaws are identified, reported and corrected within them. Evidence: patch policy, RMM patch compliance report, vulnerability tracking. SPRS: 5 pts; cannot be on a POA&M.',
            'os_supported', ['vuln_patch_os', 'vuln_patch_apps', 'vuln_remediation']],
        ['System and Information Integrity (SI)', 'SI.L2-3.14.2', 'Provide protection from malicious code at designated locations within organizational systems.',
            'Objectives: designated locations are identified and malicious code protection is deployed there. Evidence: EDR device list reconciled to inventory, email filtering configuration. SPRS: 5 pts; cannot be on a POA&M.',
            null, ['ep_malware', 'ep_edr', 'email_filter']],
        ['System and Information Integrity (SI)', 'SI.L2-3.14.3', 'Monitor system security alerts and advisories and take action in response.',
            'Objectives: sources of alerts and advisories are identified, monitored and acted on. Evidence: subscriptions (CISA, vendor advisories), tickets showing response. SPRS: 5 pts; cannot be on a POA&M.',
            null, ['vuln_remediation', 'log_review']],
        ['System and Information Integrity (SI)', 'SI.L2-3.14.4', 'Update malicious code protection mechanisms when new releases are available.',
            'Objectives: malicious code protection updates automatically when releases are available. Evidence: EDR/AV console showing current versions and auto-update policy. SPRS: 5 pts; cannot be on a POA&M.',
            null, ['ep_malware', 'ep_edr']],
        ['System and Information Integrity (SI)', 'SI.L2-3.14.5', 'Perform periodic scans of organizational systems and real-time scans of files from external sources as files are downloaded, opened, or executed.',
            'Objectives: scan frequency is defined and periodic and real-time scans are performed. Evidence: AV/EDR scan policy and recent scan results. SPRS: 3 pts; cannot be on a POA&M.',
            null, ['ep_malware', 'ep_edr']],
        ['System and Information Integrity (SI)', 'SI.L2-3.14.6', 'Monitor organizational systems, including inbound and outbound communications traffic, to detect attacks and indicators of potential attacks.',
            'Objectives: systems and inbound/outbound traffic are monitored for attacks and indicators of attack. Evidence: IDS/IPS, EDR or SOC monitoring configuration and alert records. SPRS: 5 pts; cannot be on a POA&M.',
            null, ['net_ids', 'log_review', 'ep_edr']],
        ['System and Information Integrity (SI)', 'SI.L2-3.14.7', 'Identify unauthorized use of organizational systems.',
            'Objectives: authorized use is defined and unauthorized use is identified. Evidence: SIEM/UEBA alerts for anomalous logons, sign-in risk reports, review records. SPRS: 3 pts; cannot be on a POA&M.',
            null, ['log_review']],
    ],
];
