<?php
/**
 * Microsoft 365 secure-configuration review. Control IDs cited in guidance come from the CISA SCuBA
 * M365 baselines (ScubaGear main branch, policy IDs with version suffix) and the CIS Microsoft 365
 * Foundations Benchmark v7.0.0 (May 2026) unless noted. CIS content is paraphrased.
 */
return [
    'slug' => 'm365-baseline',
    'name' => 'Microsoft 365 Secure Configuration Baseline',
    'description' => 'A secure-configuration review for client Microsoft 365 tenants: identity, email, collaboration, devices, data protection, logging and backup. '
        . 'Aligned with the CISA SCuBA Secure Configuration Baselines for M365 and the CIS Microsoft 365 Foundations Benchmark v7.0.0 (May 2026), and cross-checked against Microsoft Secure Score; '
        . 'source control IDs are cited in each item\'s guidance. Some items need Entra ID P1 (Conditional Access; included in Business Premium and E3), Entra ID P2 (Identity Protection, PIM; E5 or add-on), '
        . 'or Defender for Office 365 / Defender for Endpoint / Purview licensing; the guidance says which. Tenants without P1 should at least have Security Defaults on. '
        . 'Titles and guidance are paraphrased summaries for tracking a review, not the official benchmark text.',
    'controls' => [
        // ---- Identity (Entra ID) --------------------------------------------------------
        ['Identity (Entra ID)', 'M365-ID-01', 'MFA required for all users through Conditional Access (or Security Defaults when no Entra ID P1)', 'SCuBA MS.AAD.3.2v2 / CIS 5.2.2.2; legacy per-user MFA disabled (CIS 5.1.2.1). Evidence: CA policy export showing all users/all cloud apps with only documented break-glass exclusions. Needs Entra ID P1.', null, ['iam_mfa', 'cloud_config']],
        ['Identity (Entra ID)', 'M365-ID-02', 'Phishing-resistant MFA (FIDO2 passkeys, Windows Hello for Business or certificate) required for administrator roles', 'SCuBA MS.AAD.3.6v1 / CIS 5.2.2.5 (authentication strength in CA). SCuBA MS.AAD.3.1v1 extends this to all users as the goal. Needs Entra ID P1.', null, ['iam_mfa_admin', 'iam_mfa', 'cloud_config']],
        ['Identity (Entra ID)', 'M365-ID-03', 'Weak authentication methods (SMS, voice call, email OTP) disabled and Microsoft Authenticator shows number matching and sign-in context', 'SCuBA MS.AAD.3.5v2, MS.AAD.3.3v2 / CIS 5.2.3.5, 5.2.3.1. Authentication methods migration set to complete (MS.AAD.3.4v1).', null, ['iam_mfa', 'iam_passwords', 'cloud_config']],
        ['Identity (Entra ID)', 'M365-ID-04', 'Legacy authentication blocked', 'SCuBA MS.AAD.1.1v1 / CIS 5.2.2.3. Check sign-in logs for legacy protocol use before enforcing. Needs Entra ID P1 (Security Defaults also blocks it).', null, ['cloud_config', 'cfg_ports_services', 'iam_mfa']],
        ['Identity (Entra ID)', 'M365-ID-05', 'Device code authentication flow blocked (except documented exceptions such as Teams Rooms)', 'SCuBA MS.AAD.3.9v1 / CIS 5.2.2.12. Needs Entra ID P1.', null, ['cloud_config']],
        ['Identity (Entra ID)', 'M365-ID-06', 'Conditional Access requires a compliant or hybrid-joined device for access to company data (at least for admins and sensitive apps)', 'SCuBA MS.AAD.3.7v1, MS.AAD.3.8v1 / CIS 5.2.2.9, 5.2.2.10 (also for registering security info). Evidence: CA policy export and report-only results. Needs Entra ID P1 and Intune.', null, ['cloud_config', 'ep_mdm', 'iam_mfa']],
        ['Identity (Entra ID)', 'M365-ID-07', 'Between two and four Global Administrators', 'CIS 1.1.3 (2–4); SCuBA MS.AAD.7.1v1 allows 2–8. Evidence: role membership export.', null, ['iam_privileged', 'iam_least_privilege']],
        ['Identity (Entra ID)', 'M365-ID-08', 'Admin accounts are dedicated, cloud-only (not synced from on-premises AD) and not mailbox-licensed for daily work', 'SCuBA MS.AAD.7.3v1 / CIS 1.1.1, 1.1.4. Daily-use accounts hold no admin roles.', null, ['iam_privileged', 'cloud_config']],
        ['Identity (Entra ID)', 'M365-ID-09', 'Least-privilege admin roles used (e.g. Exchange, User, Helpdesk Administrator) instead of Global Administrator', 'SCuBA MS.AAD.7.2v1. Review GDAP relationships for the MSP and any other partners at the same time.', null, ['iam_least_privilege', 'iam_privileged', 'iam_access_review']],
        ['Identity (Entra ID)', 'M365-ID-10', 'Privileged Identity Management: highly privileged roles are eligible (just-in-time) rather than permanently active, with approval and alerts for Global Administrator activation', 'SCuBA MS.AAD.7.4v1, 7.5v1, 7.6v1, 7.7v1, 7.8v1; CIS also recommends PIM (Level 2). Needs Entra ID P2 (E5 or add-on); mark N/A with reason if unlicensed.', null, ['iam_privileged', 'iam_mfa_admin', 'log_review']],
        ['Identity (Entra ID)', 'M365-ID-11', 'Two break-glass (emergency access) accounts exist, are cloud-only, excluded from Conditional Access, protected with FIDO2 or long stored secrets, and their sign-ins trigger alerts', 'CIS 1.1.2. Evidence: account names, where credentials are stored, alert rule, and last test date.', null, ['iam_privileged', 'bc_plan', 'log_review']],
        ['Identity (Entra ID)', 'M365-ID-12', 'Risk-based policies block (or force secure remediation of) high-risk users and high-risk sign-ins, with admin notification', 'SCuBA MS.AAD.2.1v1, 2.2v1, 2.3v1 / CIS 5.2.2.6, 5.2.2.7. Needs Entra ID P2 (Identity Protection).', null, ['cloud_config', 'log_review', 'iam_mfa']],
        ['Identity (Entra ID)', 'M365-ID-13', 'Admin sessions have a limited sign-in frequency and browser sessions do not persist', 'CIS 5.2.2.4. Needs Entra ID P1.', null, ['iam_session', 'iam_privileged']],
        ['Identity (Entra ID)', 'M365-ID-14', 'Guest access restricted: guests have limited directory access, only authorized users can invite, and invites limited to approved domains where practical', 'SCuBA MS.AAD.8.1v1, 8.2v1, 8.3v1 / CIS 5.1.6.1, 5.1.6.2, 5.1.6.3. Review stale guest accounts at least quarterly.', null, ['iam_accounts', 'iam_access_review', 'cloud_config']],
        ['Identity (Entra ID)', 'M365-ID-15', 'Users cannot consent to third-party apps; an admin consent workflow is configured and users cannot register applications', 'SCuBA MS.AAD.5.2v1, 5.3v1, 5.1v1 / CIS 5.1.5.1, 5.1.5.2, 5.1.2.2. Review existing enterprise app consents for over-permissioned OAuth apps.', null, ['cloud_config', 'asset_unauth_sw', 'iam_least_privilege']],
        ['Identity (Entra ID)', 'M365-ID-16', 'Self-service password reset enabled for all users, using MFA-registered methods', 'CIS 5.2.4.1 (and 5.2.4.2 for two methods in v7). Admin password resets notify other admins.', null, ['iam_passwords', 'cloud_config']],
        ['Identity (Entra ID)', 'M365-ID-17', 'Passwords set to never expire (with MFA enforced), plus a custom banned-password list and Entra Password Protection', 'SCuBA MS.AAD.6.1v1 / CIS 1.3.1, 5.2.3.2 (5.2.3.3 extends Password Protection to on-prem AD for hybrid tenants).', null, ['iam_passwords', 'cloud_config']],
        ['Identity (Entra ID)', 'M365-ID-18', 'Shared mailboxes cannot be signed into directly, and inactive or departed users are disabled', 'CIS 1.2.2. Evidence: sign-in blocked status on shared mailbox accounts and an inactive-user report (90+ days).', null, ['iam_accounts', 'iam_offboarding']],

        // ---- Exchange Online ------------------------------------------------------------
        ['Exchange Online', 'M365-EXO-01', 'SPF record published for every sending domain, ending in -all or ~all with only approved senders', 'SCuBA MS.EXO.2.2v3 / CIS 2.1.8. Include parked domains (v=spf1 -all).', null, ['email_auth']],
        ['Exchange Online', 'M365-EXO-02', 'DKIM signing enabled for all Exchange Online domains', 'SCuBA MS.EXO.3.1v1 / CIS 2.1.9.', null, ['email_auth']],
        ['Exchange Online', 'M365-EXO-03', 'DMARC published for every domain at p=quarantine or p=reject, with aggregate reports going to a monitored mailbox or service', 'SCuBA MS.EXO.4.1v1, 4.2v1 (p=reject), 4.4v1 / CIS 2.1.10.', null, ['email_auth']],
        ['Exchange Online', 'M365-EXO-04', 'SMTP AUTH disabled tenant-wide (enabled only per mailbox for documented devices/apps)', 'SCuBA MS.EXO.5.1v1 / CIS 6.5.4. Move scanners and apps to a relay connector or Graph.', null, ['cfg_ports_services', 'cloud_config']],
        ['Exchange Online', 'M365-EXO-05', 'Automatic forwarding to external domains blocked', 'SCuBA MS.EXO.1.1v2 / CIS 6.2.1. Check outbound spam policy, remote domains and inbox rules; allow exceptions only by approved mailbox.', null, ['data_dlp', 'cloud_config']],
        ['Exchange Online', 'M365-EXO-06', 'External sender warning tag shown on inbound mail', 'SCuBA MS.EXO.7.1v1 / CIS 6.2.3.', null, ['email_filter']],
        ['Exchange Online', 'M365-EXO-07', 'Mailbox auditing enabled for all users (not bypassed for any account)', 'SCuBA MS.EXO.13.1v1 / CIS 6.1.1, 6.1.2.', null, ['log_collect']],
        ['Exchange Online', 'M365-EXO-08', 'Calendar and contact sharing with all external domains disabled', 'SCuBA MS.EXO.6.1v1, 6.2v1 / CIS 1.3.3.', null, ['cloud_config', 'data_dlp']],
        ['Exchange Online', 'M365-EXO-09', 'No mail flow rules or connection-filter allow lists that bypass filtering for external domains or IPs', 'CIS 6.2.2, 2.1.12, 2.1.13, 2.1.14. Evidence: export of transport rules and anti-spam policies.', null, ['email_filter', 'cloud_config']],
        ['Exchange Online', 'M365-EXO-10', 'Direct Send to the tenant is rejected unless a documented device needs it', 'CIS 6.5.5 (Set-OrganizationConfig -RejectDirectSend). Direct Send is widely abused for spoofed internal phishing.', null, ['email_filter', 'email_auth']],

        // ---- Email threat protection (Defender for Office 365) --------------------------
        ['Email threat protection', 'M365-MDO-01', 'Standard or Strict preset security policies applied to all users for Exchange Online Protection and Defender for Office 365', 'SCuBA MS.DEFENDER.1.1v1, 1.2v1, 1.3v1. Defender for Office 365 Plan 1 is in Business Premium; Plan 2 in E5.', null, ['email_filter', 'cloud_config']],
        ['Email threat protection', 'M365-MDO-02', 'Safe Links enabled for email, Teams and Office apps with URL detonation and no click-through', 'CIS 2.1.1. Needs Defender for Office 365 Plan 1.', null, ['email_filter', 'browser_controls']],
        ['Email threat protection', 'M365-MDO-03', 'Safe Attachments enabled for email and for SharePoint, OneDrive and Teams, plus the common attachment types filter', 'SCuBA MS.DEFENDER.3.1v1 / CIS 2.1.4, 2.1.5, 2.1.2. Needs Defender for Office 365 Plan 1 (attachment filter is in EOP).', null, ['email_filter', 'ep_malware']],
        ['Email threat protection', 'M365-MDO-04', 'Anti-phishing policy with user impersonation protection for executives/finance, domain impersonation for owned domains and key partners, and mailbox intelligence', 'SCuBA MS.DEFENDER.2.1v1, 2.2v1, 2.3v1 / CIS 2.1.7. Needs Defender for Office 365 Plan 1.', null, ['email_filter', 'pay_verification']],
        ['Email threat protection', 'M365-MDO-05', 'Sensitive and priority accounts (owners, finance, admins) have Strict protection applied', 'SCuBA MS.DEFENDER.1.4v1, 1.5v1 / CIS 2.4.1, 2.4.2.', null, ['email_filter', 'iam_privileged']],

        // ---- SharePoint, OneDrive & Teams -----------------------------------------------
        ['SharePoint, OneDrive & Teams', 'M365-SPO-01', 'SharePoint external sharing limited to existing or new authenticated guests (no "Anyone" links unless justified)', 'SCuBA MS.SHAREPOINT.1.1v1 / CIS 7.2.3. Allowing new guests is a business decision; record it.', null, ['cloud_config', 'data_dlp']],
        ['SharePoint, OneDrive & Teams', 'M365-SPO-02', 'OneDrive external sharing is no more permissive than SharePoint', 'SCuBA MS.SHAREPOINT.1.2v1 / CIS 7.2.4.', null, ['cloud_config', 'data_dlp']],
        ['SharePoint, OneDrive & Teams', 'M365-SPO-03', 'Default sharing link is "Specific people" with view-only permission', 'SCuBA MS.SHAREPOINT.2.1v1, 2.2v1 / CIS 7.2.7.', null, ['cloud_config', 'data_dlp']],
        ['SharePoint, OneDrive & Teams', 'M365-SPO-04', 'Anyone links (if allowed) expire in 30 days or less, guest access expires automatically, and verification-code guests reauthenticate within 30 days', 'SCuBA MS.SHAREPOINT.3.1v1, 3.3v2 / CIS 7.2.9, 7.2.10.', null, ['cloud_config', 'iam_session']],
        ['SharePoint, OneDrive & Teams', 'M365-SPO-05', 'OneDrive sync limited to managed/domain-joined devices; unmanaged devices get browser-only or limited web access', 'CIS v6.0 7.3.2 (removed in v7.0, still a recommended practice). Unmanaged-device access controls need Entra ID P1.', null, ['ep_mdm', 'data_dlp', 'cloud_config']],
        ['SharePoint, OneDrive & Teams', 'M365-SPO-06', 'Downloading files detected as infected is blocked', 'CIS 7.3.1 (DisallowInfectedFileDownload). Works with Safe Attachments for SharePoint, OneDrive and Teams.', null, ['ep_malware', 'cloud_config']],
        ['SharePoint, OneDrive & Teams', 'M365-TMS-01', 'Teams external access limited to approved domains, and unmanaged (consumer) Teams users cannot start contact', 'SCuBA MS.TEAMS.2.1v2, 2.2v2, 2.3v2 / CIS 8.2.1, 8.2.2.', null, ['cloud_config']],
        ['SharePoint, OneDrive & Teams', 'M365-TMS-02', 'Teams meetings: anonymous users cannot start meetings and wait in the lobby; only organizers and co-organizers present by default', 'SCuBA MS.TEAMS.1.2v2, 1.3v1 / CIS 8.5.1, 8.5.6.', null, ['cloud_config']],
        ['SharePoint, OneDrive & Teams', 'M365-TMS-03', 'Guest access to Teams and Microsoft 365 Groups is governed: guest settings reviewed and third-party/custom Teams apps require approval', 'SCuBA MS.TEAMS.5.1v2, 5.2v2, 5.3v2. Evidence: Teams app permission policy and guest access settings.', null, ['cloud_config', 'asset_unauth_sw', 'iam_access_review']],

        // ---- Defender & Intune ----------------------------------------------------------
        ['Defender & Intune', 'M365-DEV-01', 'Intune compliance policies assigned to all platforms, and devices with no compliance policy are marked not compliant', 'CIS 4.1. Policies check OS version, encryption, Defender status and screen lock. Needs Intune (Business Premium / E3).', null, ['ep_mdm', 'cfg_baseline']],
        ['Defender & Intune', 'M365-DEV-02', 'Personally owned device enrollment blocked by default; BYOD phones use app protection policies (MAM)', 'CIS 4.2.', null, ['ep_mdm', 'data_dlp']],
        ['Defender & Intune', 'M365-DEV-03', 'All Windows and macOS devices onboarded to Microsoft Defender for Endpoint (or the MSP\'s EDR) with tamper protection on', 'Microsoft Secure Score / Intune security baselines (no SCuBA or CIS M365 ID). Evidence: onboarding report vs. device inventory. Defender for Business is in Business Premium.', 'stale', ['ep_edr', 'ep_malware']],
        ['Defender & Intune', 'M365-DEV-04', 'BitLocker enforced through Intune with recovery keys escrowed to Entra ID; standard users cannot read their own recovery keys', 'CIS 5.1.4.6 (key recovery restriction); encryption policy per Intune endpoint security.', null, ['ep_encryption', 'data_encrypt_rest']],
        ['Defender & Intune', 'M365-DEV-05', 'Windows LAPS enabled for local administrator accounts, and Global Administrators are not added as local admins on Entra join', 'CIS 5.1.4.5, 5.1.4.3, 5.1.4.4.', null, ['iam_privileged', 'iam_passwords', 'iam_least_privilege']],
        ['Defender & Intune', 'M365-DEV-06', 'Attack surface reduction rules deployed in block mode (after audit), including blocking Office child processes and credential theft from LSASS', 'Microsoft Secure Score / Defender for Endpoint (no SCuBA or CIS M365 ID). Evidence: Intune ASR policy and ASR report showing few audit-only rules.', null, ['cfg_baseline', 'ep_malware']],

        // ---- Data protection ------------------------------------------------------------
        ['Data protection', 'M365-DP-01', 'Sensitivity labels published (at least Public, Internal, Confidential) and applied to sensitive sites and documents', 'CIS 3.3.1. Needs Purview Information Protection (Business Premium / E3 for manual labels; auto-labeling needs E5).', null, ['data_inventory', 'data_dlp']],
        ['Data protection', 'M365-DP-02', 'DLP policies protect PII and regulated data (SSN, card numbers, PHI) in Exchange, SharePoint, OneDrive and Teams', 'SCuBA MS.DEFENDER.4.1v2, 4.2v1 / CIS 3.2.1, 3.2.2. Start in test mode with policy tips, then enforce.', null, ['data_dlp']],
        ['Data protection', 'M365-DP-03', 'Retention policies configured to match the client\'s records retention schedule (keep what is required, delete what is not)', 'Microsoft Purview Data Lifecycle Management (no SCuBA or CIS M365 ID). Retention is not a backup.', null, ['data_retention_disposal']],

        // ---- Logging & alerting ---------------------------------------------------------
        ['Logging & alerting', 'M365-LOG-01', 'Unified audit log search enabled', 'SCuBA MS.DEFENDER.6.1v1 / CIS 3.1.1. Evidence: Get-AdminAuditLogConfig showing UnifiedAuditLogIngestionEnabled = True.', null, ['log_collect']],
        ['Logging & alerting', 'M365-LOG-02', 'Security alerts (alert policies, Identity Protection, Defender) go to a monitored mailbox, PSA or SIEM/SOC', 'SCuBA MS.DEFENDER.5.1v1, 5.2v1; MS.AAD.4.1v1 (Entra logs to the SOC). Include alerts for new inbox forwarding rules, mass downloads and admin role changes.', null, ['log_review']],
        ['Logging & alerting', 'M365-LOG-03', 'Audit logs retained long enough for investigations (default 180 days on Audit Standard; exported to a SIEM or archive for longer retention)', 'SCuBA MS.DEFENDER.6.3v1. One-year retention needs Audit Premium (E5) or export. Evidence: retention policy or SIEM ingestion.', null, ['log_retention', 'log_protect']],
        ['Logging & alerting', 'M365-LOG-04', 'Microsoft Secure Score and ScubaGear/CIS results reviewed at least quarterly with open items tracked', 'Evidence: Secure Score trend and report attached to the QBR, with gaps added to the roadmap.', null, ['gov_review', 'vuln_remediation', 'cloud_config']],

        // ---- Backup ---------------------------------------------------------------------
        ['Backup', 'M365-BAK-01', 'Third-party backup protects Exchange, OneDrive, SharePoint and Teams data daily', 'Microsoft\'s shared responsibility model does not include point-in-time backup of customer data; recycle bins and retention are not backups. Evidence: backup job report covering all licensed users and sites.', null, ['data_backup', 'data_backup_offsite']],
        ['Backup', 'M365-BAK-02', 'M365 backup restores tested at least twice a year and backup admin access protected with MFA', 'Evidence: restore test record (mailbox item and SharePoint file) and backup console MFA screenshot.', null, ['data_restore_test', 'iam_mfa_admin']],
    ],
];
