<?php
/**
 * NIST Cybersecurity Framework (CSF) 2.0 — all 106 Subcategories (NIST CSWP 29, February 26, 2024).
 * Titles quote the public-domain NIST outcome text; guidance is Mountaineer IT's plain-English summary.
 */
return [
    'slug' => 'nist-csf-2',
    'name' => 'NIST Cybersecurity Framework (CSF) 2.0',
    'description' => 'The NIST Cybersecurity Framework 2.0 (NIST CSWP 29, February 26, 2024) is a voluntary framework widely used to structure and communicate a security program. It is organized into six Functions (Govern, Identify, Protect, Detect, Respond, Recover), 22 Categories and 106 Subcategory outcomes, and suits organizations of any size or sector. There is no certification; here each outcome is used to rate the client\'s current state and drive the roadmap toward a target profile. Titles quote the NIST outcomes; guidance is a practical summary, not the official text or legal advice.',
    'controls' => [
        // ---------------- GOVERN (GV) ----------------
        ['Govern — Organizational Context (GV.OC)', 'GV.OC-01', 'The organizational mission is understood and informs cybersecurity risk management', 'Leadership can state what the business does and what matters most, and security priorities follow from it. Evidence: a short mission/business-priorities statement referenced in the security plan or QBR notes.', null, ['gov_policy']],
        ['Govern — Organizational Context (GV.OC)', 'GV.OC-02', 'Internal and external stakeholders are understood, and their needs and expectations regarding cybersecurity risk management are understood and considered', 'Know who cares about the client\'s security (owners, staff, customers, insurers, regulators) and what they expect. Evidence: stakeholder list with expectations, e.g. insurer questionnaire and key customer requirements.', null, ['gov_legal']],
        ['Govern — Organizational Context (GV.OC)', 'GV.OC-03', 'Legal, regulatory, and contractual requirements regarding cybersecurity — including privacy and civil liberties obligations — are understood and managed', 'Applicable laws, regulations and contract clauses (HIPAA, FTC Safeguards, PCI, state privacy/breach laws, cyber insurance) are identified and tracked. Evidence: a compliance obligations register reviewed at least yearly.', null, ['gov_legal', 'gov_privacy_notice']],
        ['Govern — Organizational Context (GV.OC)', 'GV.OC-04', 'Critical objectives, capabilities, and services that external stakeholders depend on or expect from the organization are understood and communicated', 'The services customers rely on (e.g. online ordering, patient scheduling) and acceptable downtime are identified. Evidence: list of critical services with recovery expectations, used in the BC/DR plan.', null, ['bc_plan']],
        ['Govern — Organizational Context (GV.OC)', 'GV.OC-05', 'Outcomes, capabilities, and services that the organization depends on are understood and communicated', 'The business knows what it depends on to operate: ISP, Microsoft 365, line-of-business apps, MSP, power. Evidence: dependency list tied to the vendor inventory and BC plan.', null, ['bc_plan', 'vendor_mgmt']],

        ['Govern — Risk Management Strategy (GV.RM)', 'GV.RM-01', 'Risk management objectives are established and agreed to by organizational stakeholders', 'Owners and the MSP agree on what the security program is trying to achieve (e.g. meet insurance requirements, avoid downtime over one day). Evidence: documented objectives in the security plan or signed-off roadmap.', null, ['gov_policy', 'gov_risk_treatment']],
        ['Govern — Risk Management Strategy (GV.RM)', 'GV.RM-02', 'Risk appetite and risk tolerance statements are established, communicated, and maintained', 'Leadership states how much risk it will accept (e.g. max data loss, downtime, spend). Evidence: short written risk appetite statement, reviewed yearly.', null, ['gov_risk_treatment']],
        ['Govern — Risk Management Strategy (GV.RM)', 'GV.RM-03', 'Cybersecurity risk management activities and outcomes are included in enterprise risk management processes', 'Cyber risk is discussed alongside other business risks (financial, legal, operational), not only by IT. Evidence: cyber items on the owner/board agenda or in the business risk register.', null, ['gov_risk_assessment', 'gov_review']],
        ['Govern — Risk Management Strategy (GV.RM)', 'GV.RM-04', 'Strategic direction that describes appropriate risk response options is established and communicated', 'It is clear when risks are mitigated, transferred (e.g. cyber insurance), avoided or accepted, and who can decide. Evidence: risk treatment guidance in the policy and decisions recorded in the risk register.', null, ['gov_risk_treatment']],
        ['Govern — Risk Management Strategy (GV.RM)', 'GV.RM-05', 'Lines of communication across the organization are established for cybersecurity risks, including risks from suppliers and other third parties', 'Staff, leadership and the MSP know how security risks and vendor issues get raised and to whom. Evidence: documented reporting path and regular QBR/security meetings.', null, ['gov_roles']],
        ['Govern — Risk Management Strategy (GV.RM)', 'GV.RM-06', 'A standardized method for calculating, documenting, categorizing, and prioritizing cybersecurity risks is established and communicated', 'Risks are scored the same way every time (e.g. likelihood x impact) so they can be ranked. Evidence: risk assessment method and a scored risk register.', null, ['gov_risk_assessment', 'gov_risk_treatment']],
        ['Govern — Risk Management Strategy (GV.RM)', 'GV.RM-07', 'Strategic opportunities (i.e., positive risks) are characterized and are included in organizational cybersecurity risk discussions', 'Security discussions also cover opportunities, such as new tools or cloud moves that reduce risk or cost. Evidence: roadmap/QBR notes showing opportunities considered.', null, ['gov_review']],

        ['Govern — Roles, Responsibilities, and Authorities (GV.RR)', 'GV.RR-01', 'Organizational leadership is responsible and accountable for cybersecurity risk and fosters a culture that is risk-aware, ethical, and continually improving', 'The owner or executive team takes accountability for security rather than leaving it entirely to the MSP. Evidence: leadership sign-off on the security policy and attendance at security reviews.', null, ['gov_roles']],
        ['Govern — Roles, Responsibilities, and Authorities (GV.RR)', 'GV.RR-02', 'Roles, responsibilities, and authorities related to cybersecurity risk management are established, communicated, understood, and enforced', 'A named internal security lead exists and the split of duties between client and MSP is written down. Evidence: roles/RACI in the WISP and MSP service agreement.', null, ['gov_roles', 'vendor_contracts']],
        ['Govern — Roles, Responsibilities, and Authorities (GV.RR)', 'GV.RR-03', 'Adequate resources are allocated commensurate with the cybersecurity risk strategy, roles, responsibilities, and policies', 'Budget and time are allotted for security work on the roadmap. Evidence: approved IT/security budget and funded roadmap items.', null, ['gov_risk_treatment']],
        ['Govern — Roles, Responsibilities, and Authorities (GV.RR)', 'GV.RR-04', 'Cybersecurity is included in human resources practices', 'Security is built into hiring, onboarding and departures: background checks where appropriate, signed acceptable-use policy, prompt offboarding. Evidence: HR checklists and signed agreements.', null, ['hr_screening', 'hr_agreements', 'iam_offboarding', 'hr_sanctions']],

        ['Govern — Policy (GV.PO)', 'GV.PO-01', 'Policy for managing cybersecurity risks is established based on organizational context, cybersecurity strategy, and priorities and is communicated and enforced', 'A written security policy (e.g. WISP) fits the business, is approved by leadership and shared with staff. Evidence: approved policy and staff acknowledgments.', null, ['gov_policy', 'hr_agreements']],
        ['Govern — Policy (GV.PO)', 'GV.PO-02', 'Policy for managing cybersecurity risks is reviewed, updated, communicated, and enforced to reflect changes in requirements, threats, technology, and organizational mission', 'The policy is reviewed at least yearly and after major changes. Evidence: version history with review dates and approver.', null, ['gov_policy', 'gov_review']],

        ['Govern — Oversight (GV.OV)', 'GV.OV-01', 'Cybersecurity risk management strategy outcomes are reviewed to inform and adjust strategy and direction', 'Results of the security program (incidents, gaps closed, scores) are reviewed and used to adjust the plan. Evidence: QBR/annual review notes with resulting roadmap changes.', null, ['gov_review']],
        ['Govern — Oversight (GV.OV)', 'GV.OV-02', 'The cybersecurity risk management strategy is reviewed and adjusted to ensure coverage of organizational requirements and risks', 'The strategy is checked periodically against new requirements, threats and business changes. Evidence: annual strategy/roadmap review record.', null, ['gov_review', 'gov_risk_assessment']],
        ['Govern — Oversight (GV.OV)', 'GV.OV-03', 'Organizational cybersecurity risk management performance is evaluated and reviewed for adjustments needed', 'Security performance is measured with a few metrics (patch compliance, MFA coverage, training completion) and reviewed. Evidence: metrics report or scorecard reviewed at QBRs.', null, ['gov_review']],

        ['Govern — Cybersecurity Supply Chain Risk Management (GV.SC)', 'GV.SC-01', 'A cybersecurity supply chain risk management program, strategy, objectives, policies, and processes are established and agreed to by organizational stakeholders', 'There is a written approach for managing security risk from vendors and service providers. Evidence: vendor management section in the security policy.', null, ['vendor_mgmt', 'gov_policy']],
        ['Govern — Cybersecurity Supply Chain Risk Management (GV.SC)', 'GV.SC-02', 'Cybersecurity roles and responsibilities for suppliers, customers, and partners are established, communicated, and coordinated internally and externally', 'Who is responsible for what with each key vendor (MSP, software vendors, cloud providers) is documented. Evidence: responsibility matrices or contract clauses.', null, ['vendor_contracts', 'gov_roles']],
        ['Govern — Cybersecurity Supply Chain Risk Management (GV.SC)', 'GV.SC-03', 'Cybersecurity supply chain risk management is integrated into cybersecurity and enterprise risk management, risk assessment, and improvement processes', 'Vendor risks appear in the regular risk assessment and risk register. Evidence: vendor entries in the risk register.', null, ['vendor_mgmt', 'gov_risk_assessment']],
        ['Govern — Cybersecurity Supply Chain Risk Management (GV.SC)', 'GV.SC-04', 'Suppliers are known and prioritized by criticality', 'A vendor inventory exists with each vendor rated by how critical it is and what data it holds. Evidence: vendor list with criticality ratings.', null, ['vendor_mgmt']],
        ['Govern — Cybersecurity Supply Chain Risk Management (GV.SC)', 'GV.SC-05', 'Requirements to address cybersecurity risks in supply chains are established, prioritized, and integrated into contracts and other types of agreements with suppliers and other relevant third parties', 'Contracts with key vendors include security, breach-notification and data-handling terms (BAAs where needed). Evidence: contract clauses or signed agreements.', null, ['vendor_contracts']],
        ['Govern — Cybersecurity Supply Chain Risk Management (GV.SC)', 'GV.SC-06', 'Planning and due diligence are performed to reduce risks before entering into formal supplier or other third-party relationships', 'New vendors are vetted before signing (security questionnaire, SOC 2 report, references). Evidence: completed due-diligence records.', null, ['vendor_mgmt']],
        ['Govern — Cybersecurity Supply Chain Risk Management (GV.SC)', 'GV.SC-07', 'The risks posed by a supplier, their products and services, and other third parties are understood, recorded, prioritized, assessed, responded to, and monitored over the course of the relationship', 'Critical vendors are reassessed periodically and issues (breaches, lapses) are tracked. Evidence: annual vendor review notes and updated risk entries.', null, ['vendor_mgmt', 'gov_risk_treatment']],
        ['Govern — Cybersecurity Supply Chain Risk Management (GV.SC)', 'GV.SC-08', 'Relevant suppliers and other third parties are included in incident planning, response, and recovery activities', 'The IR plan lists vendor contacts (MSP, insurer, key software vendors) and their roles. Evidence: vendor contacts in the IR plan; vendors included in tabletop exercises.', null, ['ir_plan', 'vendor_mgmt']],
        ['Govern — Cybersecurity Supply Chain Risk Management (GV.SC)', 'GV.SC-09', 'Supply chain security practices are integrated into cybersecurity and enterprise risk management programs, and their performance is monitored throughout the technology product and service life cycle', 'Vendor security performance is checked across the life of the product or service, from purchase to retirement. Evidence: vendor reviews tied to renewals and lifecycle planning.', null, ['vendor_mgmt']],
        ['Govern — Cybersecurity Supply Chain Risk Management (GV.SC)', 'GV.SC-10', 'Cybersecurity supply chain risk management plans include provisions for activities that occur after the conclusion of a partnership or service agreement', 'When a vendor relationship ends, access is revoked and data is returned or destroyed. Evidence: vendor offboarding checklist and data-destruction confirmation.', null, ['vendor_contracts', 'iam_offboarding', 'data_retention_disposal']],

        // ---------------- IDENTIFY (ID) ----------------
        ['Identify — Asset Management (ID.AM)', 'ID.AM-01', 'Inventories of hardware managed by the organization are maintained', 'All computers, servers, network gear and mobile devices are tracked with owner and location. Evidence: RMM/ITFlow asset inventory kept current.', 'stale', ['asset_hw_inventory']],
        ['Identify — Asset Management (ID.AM)', 'ID.AM-02', 'Inventories of software, services, and systems managed by the organization are maintained', 'Installed software, SaaS subscriptions and cloud services are tracked. Evidence: RMM software inventory plus a SaaS/license list.', null, ['asset_sw_inventory']],
        ['Identify — Asset Management (ID.AM)', 'ID.AM-03', 'Representations of the organization\'s authorized network communication and internal and external network data flows are maintained', 'A current network diagram and a simple map of where data flows (office, cloud, vendors). Evidence: network diagram and data-flow diagram in documentation.', null, ['data_inventory', 'net_segmentation']],
        ['Identify — Asset Management (ID.AM)', 'ID.AM-04', 'Inventories of services provided by suppliers are maintained', 'A list of services provided by vendors (MSP, ISP, cloud apps, payment processor). Evidence: vendor/service inventory.', null, ['vendor_mgmt']],
        ['Identify — Asset Management (ID.AM)', 'ID.AM-05', 'Assets are prioritized based on classification, criticality, resources, and impact on the mission', 'Critical systems and data are flagged so protection and recovery effort go where it matters most. Evidence: criticality field in the asset inventory.', null, ['asset_hw_inventory', 'data_inventory']],
        ['Identify — Asset Management (ID.AM)', 'ID.AM-07', 'Inventories of data and corresponding metadata for designated data types are maintained', 'Sensitive data (PII, PHI, cardholder, financial) is identified along with where it lives and who owns it. Evidence: data inventory/classification map.', null, ['data_inventory']],
        ['Identify — Asset Management (ID.AM)', 'ID.AM-08', 'Systems, hardware, software, services, and data are managed throughout their life cycles', 'Assets are planned, maintained and retired on schedule, with data wiped at disposal. Evidence: lifecycle/replacement plan, EOL tracking and disposal certificates.', 'hw_lifecycle', ['ep_lifecycle', 'media_sanitization', 'data_retention_disposal']],

        ['Identify — Risk Assessment (ID.RA)', 'ID.RA-01', 'Vulnerabilities in assets are identified, validated, and recorded', 'Regular vulnerability scanning and patch reporting identify weaknesses. Evidence: vulnerability scan reports and patch compliance reports.', null, ['vuln_scan', 'vuln_remediation']],
        ['Identify — Risk Assessment (ID.RA)', 'ID.RA-02', 'Cyber threat intelligence is received from information sharing forums and sources', 'The MSP or client follows threat alerts (CISA, vendor advisories, ISACs) and acts on relevant ones. Evidence: subscriptions and examples of alerts actioned.', null, ['vuln_remediation']],
        ['Identify — Risk Assessment (ID.RA)', 'ID.RA-03', 'Internal and external threats to the organization are identified and recorded', 'Likely threats (phishing, ransomware, insider error, theft) are listed in the risk assessment. Evidence: threat section of the risk assessment.', null, ['gov_risk_assessment']],
        ['Identify — Risk Assessment (ID.RA)', 'ID.RA-04', 'Potential impacts and likelihoods of threats exploiting vulnerabilities are identified and recorded', 'Each significant risk has an estimated likelihood and business impact. Evidence: scored risk register.', null, ['gov_risk_assessment']],
        ['Identify — Risk Assessment (ID.RA)', 'ID.RA-05', 'Threats, vulnerabilities, likelihoods, and impacts are used to understand inherent risk and inform risk response prioritization', 'Risk scores drive which fixes happen first on the roadmap. Evidence: prioritized risk register linked to roadmap items.', null, ['gov_risk_assessment', 'gov_risk_treatment']],
        ['Identify — Risk Assessment (ID.RA)', 'ID.RA-06', 'Risk responses are chosen, prioritized, planned, tracked, and communicated', 'Each risk has a decision (fix, transfer, accept) with an owner and due date. Evidence: risk treatment plan / POA&M tracked to completion.', null, ['gov_risk_treatment', 'vuln_remediation']],
        ['Identify — Risk Assessment (ID.RA)', 'ID.RA-07', 'Changes and exceptions are managed, assessed for risk impact, recorded, and tracked', 'Significant changes and policy exceptions (e.g. MFA exclusions) are approved, risk-assessed and logged. Evidence: change tickets and an exceptions register.', null, ['cfg_change', 'gov_risk_treatment']],
        ['Identify — Risk Assessment (ID.RA)', 'ID.RA-08', 'Processes for receiving, analyzing, and responding to vulnerability disclosures are established', 'There is a way to receive and act on vulnerability reports from vendors, researchers or customers. Evidence: documented process/contact and handled examples.', null, ['vuln_remediation']],
        ['Identify — Risk Assessment (ID.RA)', 'ID.RA-09', 'The authenticity and integrity of hardware and software are assessed prior to acquisition and use', 'Hardware and software come from reputable sources and downloads are verified. Evidence: approved-vendor purchasing practice and software sourcing rules.', null, ['asset_unauth_sw', 'vendor_mgmt']],
        ['Identify — Risk Assessment (ID.RA)', 'ID.RA-10', 'Critical suppliers are assessed prior to acquisition', 'Critical vendors are security-reviewed before purchase. Evidence: pre-purchase vendor assessments.', null, ['vendor_mgmt']],

        ['Identify — Improvement (ID.IM)', 'ID.IM-01', 'Improvements are identified from evaluations', 'Assessments and audits produce a list of improvements that feed the roadmap. Evidence: assessment findings converted to roadmap items.', null, ['gov_review', 'gov_risk_treatment']],
        ['Identify — Improvement (ID.IM)', 'ID.IM-02', 'Improvements are identified from security tests and exercises, including those done in coordination with suppliers and relevant third parties', 'Lessons from penetration tests, phishing simulations, restore tests and tabletops are captured and acted on. Evidence: test reports with follow-up actions.', null, ['ir_test', 'vuln_pentest', 'bc_test']],
        ['Identify — Improvement (ID.IM)', 'ID.IM-03', 'Improvements are identified from execution of operational processes, procedures, and activities', 'Day-to-day operations (tickets, near misses, recurring issues) lead to process improvements. Evidence: QBR notes or post-incident reviews with actions.', null, ['gov_review']],
        ['Identify — Improvement (ID.IM)', 'ID.IM-04', 'Incident response plans and other cybersecurity plans that affect operations are established, communicated, maintained, and improved', 'IR and BC/DR plans exist, staff know them, and they are updated at least yearly and after incidents. Evidence: current plans with review dates.', null, ['ir_plan', 'bc_plan']],

        // ---------------- PROTECT (PR) ----------------
        ['Protect — Identity Management, Authentication, and Access Control (PR.AA)', 'PR.AA-01', 'Identities and credentials for authorized users, services, and hardware are managed by the organization', 'Every user has a unique account; accounts are created, changed and disabled through a defined process, and service accounts are tracked. Evidence: onboarding/offboarding tickets and user list reconciled to HR.', null, ['iam_accounts', 'iam_offboarding']],
        ['Protect — Identity Management, Authentication, and Access Control (PR.AA)', 'PR.AA-02', 'Identities are proofed and bound to credentials based on the context of interactions', 'People are verified before accounts are issued or reset (e.g. help-desk identity verification before password/MFA resets). Evidence: documented verification procedure.', null, ['iam_accounts']],
        ['Protect — Identity Management, Authentication, and Access Control (PR.AA)', 'PR.AA-03', 'Users, services, and hardware are authenticated', 'Strong authentication everywhere: MFA for email, cloud, remote and admin access plus strong passwords. Evidence: Conditional Access/MFA report and password policy settings.', null, ['iam_mfa', 'iam_passwords', 'iam_mfa_remote', 'iam_mfa_admin']],
        ['Protect — Identity Management, Authentication, and Access Control (PR.AA)', 'PR.AA-04', 'Identity assertions are protected, conveyed, and verified', 'Single sign-on and federation tokens are secured and validated (e.g. Entra ID SSO to SaaS apps, token protection). Evidence: SSO configuration and Conditional Access policies.', null, ['iam_sso', 'cloud_config']],
        ['Protect — Identity Management, Authentication, and Access Control (PR.AA)', 'PR.AA-05', 'Access permissions, entitlements, and authorizations are defined in a policy, managed, enforced, and reviewed, and incorporate the principles of least privilege and separation of duties', 'Users get only the access they need, admin rights are separate and limited, and access is reviewed periodically. Evidence: access review records and admin account list.', null, ['iam_least_privilege', 'iam_privileged', 'iam_access_review']],
        ['Protect — Identity Management, Authentication, and Access Control (PR.AA)', 'PR.AA-06', 'Physical access to assets is managed, monitored, and enforced commensurate with risk', 'Offices, server closets and network gear are locked with access limited and visitors controlled. Evidence: key/badge list, locked rack photos, visitor log.', null, ['phys_access', 'phys_visitors']],

        ['Protect — Awareness and Training (PR.AT)', 'PR.AT-01', 'Personnel are provided with awareness and training so that they possess the knowledge and skills to perform general tasks with cybersecurity risks in mind', 'All staff complete security awareness training at least yearly, with phishing simulations. Evidence: training completion and phishing campaign reports.', null, ['awareness_training', 'awareness_phishing']],
        ['Protect — Awareness and Training (PR.AT)', 'PR.AT-02', 'Individuals in specialized roles are provided with awareness and training so that they possess the knowledge and skills to perform relevant tasks with cybersecurity risks in mind', 'Admins, finance staff and executives get role-specific training (e.g. wire-fraud verification, admin hygiene). Evidence: role-based training records.', null, ['awareness_training', 'pay_verification']],

        ['Protect — Data Security (PR.DS)', 'PR.DS-01', 'The confidentiality, integrity, and availability of data-at-rest are protected', 'Stored data is protected with disk encryption, encrypted backups and appropriate permissions. Evidence: BitLocker/FileVault compliance report and storage encryption settings.', null, ['ep_encryption', 'data_encrypt_rest', 'data_dlp']],
        ['Protect — Data Security (PR.DS)', 'PR.DS-02', 'The confidentiality, integrity, and availability of data-in-transit are protected', 'Data moving over networks is encrypted (TLS, VPN, encrypted email for sensitive data). Evidence: TLS configuration, VPN settings, email encryption policy.', null, ['net_encrypt_transit', 'data_dlp']],
        ['Protect — Data Security (PR.DS)', 'PR.DS-10', 'The confidentiality, integrity, and availability of data-in-use are protected', 'Data being used is protected from unauthorized viewing or copying (screen lock, DLP, session controls). Evidence: DLP and idle-lock policies.', null, ['data_dlp', 'iam_session']],
        ['Protect — Data Security (PR.DS)', 'PR.DS-11', 'Backups of data are created, protected, maintained, and tested', 'Servers, endpoints as needed and cloud data (M365) are backed up, with an offsite immutable copy and regular restore tests. Evidence: backup job reports and restore test records.', null, ['data_backup', 'data_backup_offsite', 'data_restore_test']],

        ['Protect — Platform Security (PR.PS)', 'PR.PS-01', 'Configuration management practices are established and applied', 'Devices, servers and cloud tenants follow secure baselines, and changes are controlled. Evidence: baseline standards, RMM policies, M365 secure score and change tickets.', null, ['cfg_baseline', 'cfg_change', 'cloud_config', 'cfg_ports_services']],
        ['Protect — Platform Security (PR.PS)', 'PR.PS-02', 'Software is maintained, replaced, and removed commensurate with risk', 'OS and applications are patched promptly and unsupported software is replaced or removed. Evidence: patch compliance reports and EOL software list.', 'os_supported', ['vuln_patch_os', 'vuln_patch_apps', 'ep_lifecycle']],
        ['Protect — Platform Security (PR.PS)', 'PR.PS-03', 'Hardware is maintained, replaced, and removed commensurate with risk', 'Hardware and firmware are kept current and replaced before end of life. Evidence: lifecycle report, firmware versions and warranty status.', 'hw_lifecycle', ['ep_lifecycle', 'media_sanitization']],
        ['Protect — Platform Security (PR.PS)', 'PR.PS-04', 'Log records are generated and made available for continuous monitoring', 'Audit logging is enabled on endpoints, servers, firewalls and M365, and logs are retained and protected. Evidence: audit log settings and log retention configuration.', null, ['log_collect', 'log_retention', 'log_protect', 'log_time_sync']],
        ['Protect — Platform Security (PR.PS)', 'PR.PS-05', 'Installation and execution of unauthorized software are prevented', 'Users cannot install software without approval (no local admin, application control). Evidence: local admin report and application allow-listing policy.', null, ['asset_unauth_sw', 'iam_privileged']],
        ['Protect — Platform Security (PR.PS)', 'PR.PS-06', 'Secure software development practices are integrated, and their performance is monitored throughout the software development life cycle', 'Applies only if the client develops software or websites: secure coding, code review and vulnerability testing. Evidence: SDLC documentation; otherwise mark not applicable.', null, ['dev_secure']],

        ['Protect — Technology Infrastructure Resilience (PR.IR)', 'PR.IR-01', 'Networks and environments are protected from unauthorized logical access and usage', 'Business-class firewall, segmented networks, isolated guest Wi-Fi and secure remote access. Evidence: firewall config, VLAN design and remote access settings.', null, ['net_firewall', 'net_segmentation', 'net_remote_access', 'net_wireless']],
        ['Protect — Technology Infrastructure Resilience (PR.IR)', 'PR.IR-02', 'The organization\'s technology assets are protected from environmental threats', 'Servers and network gear have UPS, adequate cooling and protection from fire and water. Evidence: UPS status, server room photos and environmental monitoring.', null, ['phys_environment']],
        ['Protect — Technology Infrastructure Resilience (PR.IR)', 'PR.IR-03', 'Mechanisms are implemented to achieve resilience requirements in normal and adverse situations', 'Redundancy matches business needs (failover internet, spare hardware, cloud failover). Evidence: redundancy design documented in the BC plan.', null, ['bc_plan']],
        ['Protect — Technology Infrastructure Resilience (PR.IR)', 'PR.IR-04', 'Adequate resource capacity to ensure availability is maintained', 'Storage, bandwidth and compute are monitored so systems do not run out of capacity. Evidence: RMM capacity alerts and trend reports.', null, ['bc_plan']],

        // ---------------- DETECT (DE) ----------------
        ['Detect — Continuous Monitoring (DE.CM)', 'DE.CM-01', 'Networks and network services are monitored to find potentially adverse events', 'Firewall and network traffic are monitored for suspicious activity (IDS/IPS, DNS filtering alerts). Evidence: firewall/IDS alerting and review records.', null, ['net_ids', 'net_dns_filter', 'log_review']],
        ['Detect — Continuous Monitoring (DE.CM)', 'DE.CM-02', 'The physical environment is monitored to find potentially adverse events', 'Physical access and environment are monitored (cameras, alarms, door logs, temperature alerts). Evidence: alarm/camera system and alert settings.', null, ['phys_access', 'phys_environment']],
        ['Detect — Continuous Monitoring (DE.CM)', 'DE.CM-03', 'Personnel activity and technology usage are monitored to find potentially adverse events', 'Sign-ins and user activity are monitored for anomalies (impossible travel, risky sign-ins, mass downloads). Evidence: M365/Entra sign-in alerts and SOC reports.', null, ['log_review', 'cloud_config']],
        ['Detect — Continuous Monitoring (DE.CM)', 'DE.CM-06', 'External service provider activities and services are monitored to find potentially adverse events', 'Vendor and MSP access and activity are logged and reviewed (remote tool sessions, vendor accounts). Evidence: remote access session logs and vendor account reviews.', null, ['vendor_mgmt', 'log_review', 'net_remote_access']],
        ['Detect — Continuous Monitoring (DE.CM)', 'DE.CM-09', 'Computing hardware and software, runtime environments, and their data are monitored to find potentially adverse events', 'EDR/anti-malware and RMM monitor every endpoint and server, with alerts reviewed 24/7 where possible. Evidence: EDR coverage report and MDR/SOC alert records.', 'stale', ['ep_edr', 'ep_malware', 'log_review']],

        ['Detect — Adverse Event Analysis (DE.AE)', 'DE.AE-02', 'Potentially adverse events are analyzed to better understand associated activities', 'Alerts are investigated by the MSP or SOC, not just auto-closed. Evidence: alert tickets with analysis notes.', null, ['log_review']],
        ['Detect — Adverse Event Analysis (DE.AE)', 'DE.AE-03', 'Information is correlated from multiple sources', 'Logs from endpoints, M365, firewall and identity are correlated, typically in a SIEM or MDR platform. Evidence: SIEM/MDR data sources list.', null, ['log_review', 'log_collect']],
        ['Detect — Adverse Event Analysis (DE.AE)', 'DE.AE-04', 'The estimated impact and scope of adverse events are understood', 'For each significant alert, analysts determine which systems, users and data are affected. Evidence: investigation notes documenting scope.', null, ['log_review', 'ir_plan']],
        ['Detect — Adverse Event Analysis (DE.AE)', 'DE.AE-06', 'Information on adverse events is provided to authorized staff and tools', 'Alerts reach the right people and tools quickly (SOC, MSP tech, client contact). Evidence: alert routing configuration and escalation contacts.', null, ['log_review']],
        ['Detect — Adverse Event Analysis (DE.AE)', 'DE.AE-07', 'Cyber threat intelligence and other contextual information are integrated into the analysis', 'Threat intel and asset context (criticality, owner) inform alert analysis. Evidence: MDR/SIEM threat intel feeds and asset tagging.', null, ['log_review']],
        ['Detect — Adverse Event Analysis (DE.AE)', 'DE.AE-08', 'Incidents are declared when adverse events meet the defined incident criteria', 'The IR plan defines what counts as an incident and who can declare one. Evidence: incident criteria in the IR plan and incident records.', null, ['ir_plan']],

        // ---------------- RESPOND (RS) ----------------
        ['Respond — Incident Management (RS.MA)', 'RS.MA-01', 'The incident response plan is executed in coordination with relevant third parties once an incident is declared', 'When an incident is declared, the IR plan is followed with the MSP, insurer, breach counsel and forensics as needed. Evidence: incident records showing plan use and third-party contacts.', null, ['ir_plan', 'vendor_mgmt']],
        ['Respond — Incident Management (RS.MA)', 'RS.MA-02', 'Incident reports are triaged and validated', 'Reported issues (from staff, tools or vendors) are checked to confirm whether they are real incidents. Evidence: triage notes in tickets.', null, ['ir_plan']],
        ['Respond — Incident Management (RS.MA)', 'RS.MA-03', 'Incidents are categorized and prioritized', 'Incidents are assigned a type and severity so the most serious get attention first. Evidence: severity levels in the IR plan and on incident tickets.', null, ['ir_plan']],
        ['Respond — Incident Management (RS.MA)', 'RS.MA-04', 'Incidents are escalated or elevated as needed', 'There is a clear escalation path to leadership, the MSP, insurer and outside experts. Evidence: escalation matrix and contact list in the IR plan.', null, ['ir_plan']],
        ['Respond — Incident Management (RS.MA)', 'RS.MA-05', 'The criteria for initiating incident recovery are applied', 'The plan defines when to move from containment to recovery. Evidence: recovery criteria in the IR plan and incident records.', null, ['ir_plan', 'bc_plan']],

        ['Respond — Incident Analysis (RS.AN)', 'RS.AN-03', 'Analysis is performed to establish what has taken place during an incident and the root cause of the incident', 'Every significant incident gets a root-cause review. Evidence: post-incident report with root cause.', null, ['ir_plan']],
        ['Respond — Incident Analysis (RS.AN)', 'RS.AN-06', 'Actions performed during an investigation are recorded, and the records\' integrity and provenance are preserved', 'Investigation steps are logged in a ticket or timeline that cannot be altered after the fact. Evidence: incident timeline/ticket history.', null, ['ir_plan', 'log_protect']],
        ['Respond — Incident Analysis (RS.AN)', 'RS.AN-07', 'Incident data and metadata are collected, and their integrity and provenance are preserved', 'Logs, images and other evidence are preserved properly for insurers or law enforcement. Evidence: evidence-handling steps in the IR plan; log retention settings.', null, ['log_retention', 'log_protect', 'ir_plan']],
        ['Respond — Incident Analysis (RS.AN)', 'RS.AN-08', 'An incident\'s magnitude is estimated and validated', 'The number of affected systems, users and records is estimated and confirmed. Evidence: scope/impact section in incident reports.', null, ['ir_plan']],

        ['Respond — Incident Response Reporting and Communication (RS.CO)', 'RS.CO-02', 'Internal and external stakeholders are notified of incidents', 'Leadership, staff, customers, insurers and regulators are notified as required and on time. Evidence: notification procedures and breach-notification requirements in the IR plan.', null, ['ir_reporting', 'ir_plan']],
        ['Respond — Incident Response Reporting and Communication (RS.CO)', 'RS.CO-03', 'Information is shared with designated internal and external stakeholders', 'Incident updates are shared with the right parties (insurer, MSP, law enforcement, ISAC) through approved channels. Evidence: communication plan and records.', null, ['ir_reporting']],

        ['Respond — Incident Mitigation (RS.MI)', 'RS.MI-01', 'Incidents are contained', 'Affected devices and accounts can be isolated quickly (EDR isolation, account disable, network block). Evidence: containment playbooks and EDR isolation capability.', null, ['ir_plan', 'ep_edr']],
        ['Respond — Incident Mitigation (RS.MI)', 'RS.MI-02', 'Incidents are eradicated', 'Malware, attacker access and root causes are removed before systems return to service. Evidence: eradication steps recorded in incident tickets.', null, ['ir_plan', 'vuln_remediation']],

        // ---------------- RECOVER (RC) ----------------
        ['Recover — Incident Recovery Plan Execution (RC.RP)', 'RC.RP-01', 'The recovery portion of the incident response plan is executed once initiated from the incident response process', 'Recovery steps in the IR/DR plan are followed once recovery begins. Evidence: DR plan and incident recovery records.', null, ['bc_plan', 'ir_plan']],
        ['Recover — Incident Recovery Plan Execution (RC.RP)', 'RC.RP-02', 'Recovery actions are selected, scoped, prioritized, and performed', 'Systems are restored in priority order based on business impact. Evidence: recovery priority list in the DR plan.', null, ['bc_plan']],
        ['Recover — Incident Recovery Plan Execution (RC.RP)', 'RC.RP-03', 'The integrity of backups and other restoration assets is verified before using them for restoration', 'Backups are checked to be clean and intact before restoring (malware scan, known-good restore point). Evidence: restore test records and backup verification reports.', null, ['data_restore_test', 'data_backup']],
        ['Recover — Incident Recovery Plan Execution (RC.RP)', 'RC.RP-04', 'Critical mission functions and cybersecurity risk management are considered to establish post-incident operational norms', 'After an incident, leadership decides how the business will operate while recovering and what extra safeguards apply. Evidence: post-incident decisions recorded.', null, ['bc_plan']],
        ['Recover — Incident Recovery Plan Execution (RC.RP)', 'RC.RP-05', 'The integrity of restored assets is verified, systems and services are restored, and normal operating status is confirmed', 'Restored systems are checked for compromise and function before users go back to work. Evidence: restoration checklist sign-off.', null, ['bc_plan', 'data_restore_test']],
        ['Recover — Incident Recovery Plan Execution (RC.RP)', 'RC.RP-06', 'The end of incident recovery is declared based on criteria, and incident-related documentation is completed', 'Recovery is formally closed and the incident report and lessons learned are completed. Evidence: closed incident report with lessons learned.', null, ['ir_plan', 'bc_plan']],

        ['Recover — Incident Recovery Communication (RC.CO)', 'RC.CO-03', 'Recovery activities and progress in restoring operational capabilities are communicated to designated internal and external stakeholders', 'Staff, customers and partners get updates on recovery status. Evidence: communication plan and recovery status updates.', null, ['ir_reporting', 'bc_plan']],
        ['Recover — Incident Recovery Communication (RC.CO)', 'RC.CO-04', 'Public updates on incident recovery are shared using approved methods and messaging', 'Public statements are approved by leadership (and counsel/insurer) before release. Evidence: approved message templates and spokesperson named in the IR plan.', null, ['ir_reporting']],
    ],
];
