<?php
/**
 * SOC 2 readiness checklist based on the AICPA 2017 Trust Services Criteria
 * (revised points of focus, 2022). Titles and guidance are paraphrased summaries,
 * not the AICPA text.
 */
return [
    'slug' => 'soc2-tsc',
    'name' => 'SOC 2 Readiness (Trust Services Criteria)',
    'description' => 'Readiness checklist to work through before a SOC 2 Type I (design at a point in time) or Type II (operating effectiveness over a period, typically 3 to 12 months) audit. Security (the Common Criteria CC1 to CC9) is always in scope; Availability, Confidentiality, Processing Integrity and Privacy are added based on what the organization commits to its customers. Only a licensed CPA firm can perform the examination and issue a SOC 2 report. Based on the 2017 Trust Services Criteria with the 2022 revised points of focus. This is a paraphrased summary for tracking readiness, not the AICPA text and not audit or legal advice.',
    'controls' => [
        // CC1 Control environment
        ['CC1 — Control environment', 'CC1.1', 'Leadership shows a commitment to integrity and ethical values', 'Code of conduct approved by management and acknowledged by all staff at hire and annually. Evidence: signed acknowledgements, HR records of how violations are handled.', null, ['hr_agreements', 'gov_policy', 'hr_sanctions']],
        ['CC1 — Control environment', 'CC1.2', 'The board or owners oversee internal control independently of management', 'Owners or a board review security and risk at least annually. Evidence: meeting minutes or a signed annual review showing security and audit topics were discussed.', null, ['gov_review', 'gov_roles']],
        ['CC1 — Control environment', 'CC1.3', 'Management defines structure, reporting lines, authority and responsibility', 'Current org chart and a named security owner with documented responsibilities, including the MSP role if IT is outsourced. Evidence: org chart, job descriptions, RACI.', null, ['gov_roles']],
        ['CC1 — Control environment', 'CC1.4', 'The organization attracts, develops and keeps competent people', 'Hiring includes background checks where lawful, and staff get role and security training. Evidence: screening records, training completion reports, job descriptions.', null, ['hr_screening', 'awareness_training']],
        ['CC1 — Control environment', 'CC1.5', 'People are held accountable for their internal control duties', 'Security responsibilities appear in job descriptions or reviews and a disciplinary process exists. Evidence: performance review template, sanctions policy.', null, ['hr_sanctions', 'gov_roles']],

        // CC2 Communication and information
        ['CC2 — Communication and information', 'CC2.1', 'Relevant, quality information is obtained or produced to support internal control', 'System description, network and data flow diagrams and asset inventory are kept current. Evidence: diagrams, RMM asset inventory export, data flow documentation.', null, ['data_inventory', 'asset_hw_inventory', 'asset_sw_inventory']],
        ['CC2 — Communication and information', 'CC2.2', 'Internal control objectives and responsibilities are communicated inside the organization', 'Security policies are published to staff, acknowledged, and there is a way to report concerns or incidents. Evidence: policy portal, acknowledgement records, training content.', null, ['gov_policy', 'awareness_training']],
        ['CC2 — Communication and information', 'CC2.3', 'The organization communicates with external parties about internal control matters', 'Customers know commitments and how to report issues; vendors know security expectations. Evidence: MSA or terms, security page, support contact, customer notification process.', null, ['vendor_contracts', 'ir_reporting']],

        // CC3 Risk assessment
        ['CC3 — Risk assessment', 'CC3.1', 'Objectives are clear enough that related risks can be identified', 'Documented security and service objectives tied to customer commitments. Evidence: objectives in the security policy or risk assessment, service commitments list.', null, ['gov_policy', 'gov_risk_assessment']],
        ['CC3 — Risk assessment', 'CC3.2', 'Risks to objectives are identified and analyzed', 'Formal risk assessment at least annually covering threats, vulnerabilities, vendors and likelihood/impact. Evidence: dated risk assessment and risk register.', null, ['gov_risk_assessment', 'gov_risk_treatment']],
        ['CC3 — Risk assessment', 'CC3.3', 'Fraud risk is considered when assessing risks', 'The risk assessment explicitly covers fraud such as payment redirection, insider misuse and management override. Evidence: fraud section in the risk register, payment verification procedure.', null, ['gov_risk_assessment', 'pay_verification']],
        ['CC3 — Risk assessment', 'CC3.4', 'Significant changes that could affect internal control are identified and assessed', 'Major changes (new systems, vendors, acquisitions, staff turnover) trigger a risk review. Evidence: risk assessment updates tied to changes, change or project records.', null, ['gov_risk_assessment', 'cfg_change']],

        // CC4 Monitoring activities
        ['CC4 — Monitoring activities', 'CC4.1', 'Ongoing or separate evaluations confirm controls are present and working', 'Periodic control checks such as access reviews, vulnerability scans, internal audit or a compliance tool. Evidence: completed review checklists, scan reports, internal audit results.', null, ['gov_review', 'vuln_scan', 'iam_access_review']],
        ['CC4 — Monitoring activities', 'CC4.2', 'Control deficiencies are communicated and fixed in a timely way', 'Findings are logged, assigned an owner and tracked to closure. Evidence: remediation tracker or ticket history, management reporting on open items.', null, ['gov_risk_treatment', 'vuln_remediation']],

        // CC5 Control activities
        ['CC5 — Control activities', 'CC5.1', 'Control activities are chosen and built to reduce risks to acceptable levels', 'Each significant risk maps to one or more controls. Evidence: risk register with mapped controls, control matrix.', null, ['gov_risk_treatment']],
        ['CC5 — Control activities', 'CC5.2', 'General controls over technology are selected and developed', 'IT general controls cover access, change, operations and backup. Evidence: IT policies, hardening baselines, RMM and backup configuration.', null, ['cfg_baseline', 'gov_policy']],
        ['CC5 — Control activities', 'CC5.3', 'Controls are put in place through policies and procedures', 'Approved policies with owners and review dates, and procedures staff actually follow. Evidence: policy set with version history, annual review sign-off.', null, ['gov_policy', 'gov_review']],

        // CC6 Logical and physical access
        ['CC6 — Logical and physical access', 'CC6.1', 'Logical access security software, infrastructure and architecture protect information assets', 'SSO/MFA, role-based access, network segmentation and encryption of sensitive data. Evidence: identity provider settings, MFA enforcement report, network diagram, encryption settings.', null, ['iam_mfa', 'iam_least_privilege', 'net_segmentation', 'data_encrypt_rest']],
        ['CC6 — Logical and physical access', 'CC6.2', 'Users are registered and authorized before access is granted and removed when no longer needed', 'Documented onboarding approval and same-day offboarding. Evidence: access request tickets, HR termination list matched to disabled accounts.', null, ['iam_accounts', 'iam_offboarding']],
        ['CC6 — Logical and physical access', 'CC6.3', 'Access is granted, changed and removed based on roles and least privilege', 'Role-based groups, separate admin accounts, and periodic access reviews. Evidence: group membership exports, quarterly access review sign-off.', null, ['iam_least_privilege', 'iam_access_review', 'iam_privileged']],
        ['CC6 — Logical and physical access', 'CC6.4', 'Physical access to facilities and sensitive assets is restricted to authorized people', 'Badge or key control for offices and server rooms; cloud-hosted systems rely on the provider SOC report. Evidence: badge access list, visitor log, data center SOC 2 report.', null, ['phys_access', 'phys_visitors']],
        ['CC6 — Logical and physical access', 'CC6.5', 'Data is removed and assets are sanitized before disposal or reuse', 'Devices are wiped or destroyed with a record before disposal. Evidence: certificates of destruction, disposal log, wipe procedure.', null, ['media_sanitization', 'data_retention_disposal']],
        ['CC6 — Logical and physical access', 'CC6.6', 'Security measures protect against threats from outside system boundaries', 'Firewall, MFA on remote access, no exposed admin ports, DNS filtering. Evidence: firewall rule export, external port scan, VPN/remote access MFA settings.', null, ['net_firewall', 'net_remote_access', 'iam_mfa_remote', 'net_dns_filter']],
        ['CC6 — Logical and physical access', 'CC6.7', 'Movement of information is restricted and protected in transit and on removable media', 'TLS for data in transit, encrypted laptops, controls on USB storage and file sharing. Evidence: TLS configuration, BitLocker/FileVault report, DLP or USB policy.', null, ['net_encrypt_transit', 'ep_encryption', 'media_protection', 'data_dlp']],
        ['CC6 — Logical and physical access', 'CC6.8', 'Unauthorized or malicious software is prevented or detected', 'EDR on all endpoints and servers and control over software installation. Evidence: EDR console coverage report, application control or software inventory review.', null, ['ep_edr', 'ep_malware', 'asset_unauth_sw']],

        // CC7 System operations
        ['CC7 — System operations', 'CC7.1', 'Configuration changes and new vulnerabilities are detected and monitored', 'Hardening baselines, configuration drift alerts, regular vulnerability scanning and patching. Evidence: baseline documents, scan reports, patch compliance reports.', 'os_supported', ['vuln_scan', 'cfg_baseline', 'vuln_patch_os']],
        ['CC7 — System operations', 'CC7.2', 'Systems are monitored for anomalies that could indicate attacks, errors or failures', 'Central logging with alerting reviewed by staff or an MDR/SOC. Evidence: SIEM or MDR alert samples, log source list, escalation records.', null, ['log_review', 'log_collect', 'net_ids']],
        ['CC7 — System operations', 'CC7.3', 'Security events are evaluated to decide whether they are incidents', 'Defined triage criteria and severity levels. Evidence: incident classification in the IR plan, ticket samples showing triage.', null, ['ir_plan', 'log_review']],
        ['CC7 — System operations', 'CC7.4', 'Identified incidents are responded to with a defined program', 'Written incident response plan with roles, contacts and customer notification, tested yearly. Evidence: IR plan, tabletop exercise report, incident tickets.', null, ['ir_plan', 'ir_test', 'ir_reporting']],
        ['CC7 — System operations', 'CC7.5', 'Recovery activities after incidents are identified and carried out', 'Restore from backup, root cause analysis and lessons learned after incidents. Evidence: post-incident reviews, restore records.', null, ['ir_plan', 'data_restore_test', 'bc_plan']],

        // CC8 Change management
        ['CC8 — Change management', 'CC8.1', 'Changes to infrastructure, data, software and procedures are authorized, tested, approved and documented', 'Change tickets or pull requests with approval, testing and rollback plans; emergency changes reviewed after the fact. Evidence: sample change tickets, PR approval history, patch schedule.', null, ['cfg_change', 'dev_secure']],

        // CC9 Risk mitigation
        ['CC9 — Risk mitigation', 'CC9.1', 'Risks from business disruption are identified and mitigated', 'Business continuity/disaster recovery plan, backups, and cyber insurance as appropriate. Evidence: BC/DR plan, backup reports, insurance policy summary.', null, ['bc_plan', 'data_backup', 'bc_test']],
        ['CC9 — Risk mitigation', 'CC9.2', 'Risks from vendors and business partners are assessed and managed', 'Vendor inventory with risk ratings, review of vendor SOC reports and security terms in contracts. Evidence: vendor list, collected SOC 2 reports, contract clauses.', null, ['vendor_mgmt', 'vendor_contracts']],

        // Availability
        ['Availability (optional)', 'A1.1', 'Capacity and usage are monitored and planned so availability commitments can be met', 'Only if Availability is in scope. Capacity and performance monitoring with alerts and periodic capacity reviews. Evidence: monitoring dashboards, alert thresholds, capacity review notes.', null,['log_review']],
        ['Availability (optional)', 'A1.2', 'Environmental protections, backups and recovery infrastructure are in place and maintained', 'Only if Availability is in scope. Redundant power/cooling or a hosted data center, daily backups with an offsite copy, supported hardware. Evidence: backup job reports, UPS/data center SOC report, warranty status.', 'warranty', ['data_backup', 'data_backup_offsite', 'phys_environment', 'bc_plan']],
        ['Availability (optional)', 'A1.3', 'Recovery plan procedures are tested', 'Only if Availability is in scope. Restore tests and DR exercises at least annually against RTO/RPO. Evidence: restore test records, DR test report with results and follow-ups.', null, ['data_restore_test', 'bc_test']],

        // Confidentiality
        ['Confidentiality (optional)', 'C1.1', 'Confidential information is identified and protected', 'Only if Confidentiality is in scope. Data classification, encryption and access limits for data labeled confidential, plus NDAs. Evidence: classification policy, data inventory, encryption settings, NDA templates.', null, ['data_inventory', 'data_encrypt_rest', 'hr_agreements']],
        ['Confidentiality (optional)', 'C1.2', 'Confidential information is disposed of when retention ends', 'Only if Confidentiality is in scope. Retention schedule followed and secure deletion at end of retention or contract. Evidence: retention policy, deletion logs, customer data return/destruction records.', null, ['data_retention_disposal', 'media_sanitization']],

        // Processing integrity
        ['Processing integrity (optional)', 'PI1.1', 'Information about processing objectives and data definitions is produced and used', 'Only if Processing Integrity is in scope. Documented specifications of inputs, processing and outputs for the in-scope system. Evidence: system specs, data dictionary, product documentation.', null, ['data_inventory']],
        ['Processing integrity (optional)', 'PI1.2', 'System inputs are complete and accurate', 'Only if Processing Integrity is in scope. Input validation and error handling for data entering the system. Evidence: validation rules, rejected-input logs, test cases.', null, ['dev_secure']],
        ['Processing integrity (optional)', 'PI1.3', 'Processing is complete, accurate, timely and authorized', 'Only if Processing Integrity is in scope. Job monitoring, reconciliations and exception handling. Evidence: batch job logs, reconciliation reports, exception tickets.', null, ['dev_secure', 'log_review']],
        ['Processing integrity (optional)', 'PI1.4', 'Outputs are complete, accurate, timely and delivered only to intended recipients', 'Only if Processing Integrity is in scope. Output checks and controls on who receives reports or files. Evidence: output review procedures, distribution lists, delivery logs.', null, ['dev_secure']],
        ['Processing integrity (optional)', 'PI1.5', 'Stored inputs, in-process items and outputs are kept complete, accurate and available', 'Only if Processing Integrity is in scope. Integrity checks, access controls and backups on stored data. Evidence: backup reports, database integrity checks, access lists.', null, ['data_backup', 'data_restore_test']],

        // Privacy
        ['Privacy (optional)', 'P1.1', 'A privacy notice describes practices for personal information', 'Only if Privacy is in scope. Current, published privacy notice covering collection, use, retention, sharing and contact details. Evidence: privacy notice with version date.', null, ['gov_privacy_notice']],
        ['Privacy (optional)', 'P2.1', 'Choices about personal information are communicated and consent is obtained where needed', 'Only if Privacy is in scope. Consent captured and recorded where required, with opt-out options. Evidence: consent records, cookie banner settings, opt-out handling.', null, ['gov_privacy_notice']],
        ['Privacy (optional)', 'P3.1', 'Personal information is collected only for the stated purposes', 'Only if Privacy is in scope. Forms and systems collect only fields needed for disclosed purposes. Evidence: data inventory mapped to purposes, form reviews.', null, ['data_inventory', 'gov_privacy_notice']],
        ['Privacy (optional)', 'P3.2', 'Explicit consent is obtained for sensitive personal information where required', 'Only if Privacy is in scope. Explicit consent flow and records for sensitive data categories. Evidence: consent language, stored consent records.', null, ['gov_privacy_notice', 'data_inventory']],
        ['Privacy (optional)', 'P4.1', 'Personal information is used only for the stated purposes', 'Only if Privacy is in scope. Internal use limited to disclosed purposes, with access limited by role. Evidence: data use policy, access lists.', null, ['data_inventory', 'iam_least_privilege']],
        ['Privacy (optional)', 'P4.2', 'Personal information is retained only as long as needed', 'Only if Privacy is in scope. Retention schedule applied to personal data. Evidence: retention policy, automated retention settings.', null, ['data_retention_disposal']],
        ['Privacy (optional)', 'P4.3', 'Personal information is securely disposed of', 'Only if Privacy is in scope. Secure deletion or destruction when retention ends or on request. Evidence: deletion logs, destruction certificates.', null, ['data_retention_disposal', 'media_sanitization']],
        ['Privacy (optional)', 'P5.1', 'Individuals can access their personal information', 'Only if Privacy is in scope. Process to verify identity and fulfill access requests within set timelines. Evidence: request log, response templates.', null, ['gov_privacy_notice']],
        ['Privacy (optional)', 'P5.2', 'Individuals can correct or update their personal information', 'Only if Privacy is in scope. Correction requests handled and communicated to third parties where needed. Evidence: correction request log.', null, ['gov_privacy_notice']],
        ['Privacy (optional)', 'P6.1', 'Personal information is disclosed to third parties only as permitted', 'Only if Privacy is in scope. Sharing limited to disclosed purposes or with consent. Evidence: list of subprocessors, data sharing agreements.', null, ['vendor_contracts', 'vendor_mgmt']],
        ['Privacy (optional)', 'P6.2', 'Authorized disclosures of personal information are recorded', 'Only if Privacy is in scope. Log of disclosures to third parties. Evidence: disclosure register.', null, ['vendor_mgmt']],
        ['Privacy (optional)', 'P6.3', 'Unauthorized disclosures are recorded', 'Only if Privacy is in scope. Incidents involving personal data are logged. Evidence: incident register with privacy flag.', null, ['ir_plan']],
        ['Privacy (optional)', 'P6.4', 'Third parties handling personal information commit to privacy obligations', 'Only if Privacy is in scope. Data processing agreements with vendors that touch personal data. Evidence: signed DPAs, vendor reviews.', null, ['vendor_contracts', 'vendor_mgmt']],
        ['Privacy (optional)', 'P6.5', 'Third parties report unauthorized disclosures to the organization', 'Only if Privacy is in scope. Contracts require vendors to notify of breaches. Evidence: breach notification clauses in DPAs.', null, ['vendor_contracts', 'ir_reporting']],
        ['Privacy (optional)', 'P6.6', 'Affected individuals and regulators are notified of breaches as required', 'Only if Privacy is in scope. Breach notification procedure aligned to applicable laws. Evidence: notification procedure, legal requirements list.', null, ['ir_reporting', 'gov_legal']],
        ['Privacy (optional)', 'P6.7', 'Individuals can get an accounting of the personal information held and disclosed', 'Only if Privacy is in scope. Ability to report what data is held about a person and who received it. Evidence: sample accounting response, data map.', null, ['gov_privacy_notice', 'data_inventory']],
        ['Privacy (optional)', 'P7.1', 'Personal information is kept accurate, complete and relevant', 'Only if Privacy is in scope. Data quality checks and ways for people to update their data. Evidence: data quality procedures, self-service profile features.', null, ['data_inventory']],
        ['Privacy (optional)', 'P8.1', 'Privacy inquiries, complaints and disputes are handled and compliance is monitored', 'Only if Privacy is in scope. Privacy contact, complaint handling process and periodic privacy compliance review. Evidence: complaint log, privacy review records.', null, ['gov_privacy_notice', 'gov_review']],
    ],
];
