<?php
declare(strict_types=1);

namespace Align\Alignment;

/**
 * 2.3.0: the starter standards a new install gets (migration 056), built from the MSP Security Baseline compliance
 * framework plus continuity, documentation and Microsoft 365 standards. They're only a starting point: admins edit,
 * remove and add their own under Settings → Standards. The tags are the compliance tags (Compliance::cleanTags
 * format), so answers can be shared with the compliance checklists; the automatic checks are Alignment::CHECKS keys.
 *
 * Plain data, no input: nothing here is untrusted.
 */
final class Starter
{
    /** Category names in display order. */
    public const CATEGORIES = ['Identity & access', 'Endpoints', 'Backup & recovery', 'Network', 'Email & Microsoft 365', 'People & process', 'Continuity & documentation'];

    /**
     * The standards: [category, title, priority, automatic check, tags, why it matters (client words), how to check
     * (staff notes), suggested fix title, fix project category (Roadmap::CATEGORIES key), typical cost or null].
     */
    public static function standards(): array
    {
        return [
            ['Identity & access', 'MFA on Microsoft 365 for every user', 'critical', 'm365_mfa_enforced', 'iam_mfa,cloud_config',
                'A stolen password alone can\'t get into email, files or Teams.',
                'In Entra ID, check Conditional Access or security defaults require MFA for all users. Note any excluded accounts and why (break-glass only).',
                'Turn on MFA for every Microsoft 365 user', 'security', 450],
            ['Identity & access', 'MFA for all remote access (VPN, remote tools)', 'critical', null, 'iam_mfa_remote,net_remote_access',
                'Remote access is the most common way attackers get in.',
                'Check the VPN, RD gateway and every remote support tool ask for a second factor.',
                'Require MFA on the VPN and remote tools', 'security', 600],
            ['Identity & access', 'Separate admin accounts; daily accounts have no admin rights', 'high', null, 'iam_privileged,iam_least_privilege',
                'A phishing click on a daily account can\'t take over the network.',
                'Review Domain Admins and Global Admins: only dedicated admin accounts, none used for email or browsing.',
                'Split admin accounts from daily accounts', 'security', 300],
            ['Identity & access', 'Local admin rights removed from users', 'high', null, 'iam_least_privilege,iam_privileged',
                'Malware can\'t install itself or turn off protection.',
                'Check the local Administrators group on a sample of workstations, or the RMM\'s local admin report.',
                'Remove local admin rights', 'security', 400],
            ['Identity & access', 'Business password manager for staff', 'medium', null, 'iam_passwords',
                'Strong, unique passwords without sticky notes or spreadsheets.',
                'Confirm a business password manager is licensed and most staff have signed in this quarter.',
                'Roll out a business password manager', 'security', 900],
            ['Identity & access', 'Departed users disabled the same day', 'high', null, 'iam_offboarding,iam_accounts',
                'Former staff can\'t get back into company data.',
                'Compare the last few departures with when their accounts were disabled. Is there a written checklist?',
                'Document and automate offboarding', 'security', 250],
            ['Endpoints', 'EDR on every workstation and server', 'critical', null, 'ep_edr,ep_malware',
                'Stops ransomware that ordinary antivirus misses.',
                'Compare the EDR console\'s device count with the RMM\'s.',
                'Deploy EDR to every device', 'security', 1200],
            ['Endpoints', 'Operating system patches within 14 days (critical within 7)', 'high', null, 'vuln_patch_os',
                'Closes known holes before attackers use them.',
                'Check the RMM patch report: devices missing patches older than 14 days.',
                'Tighten the patch policy', 'security', null],
            ['Endpoints', 'Third-party applications patched automatically', 'medium', null, 'vuln_patch_apps',
                'Browsers, PDF readers and similar apps are common targets.',
                'Check third-party patching is on in the RMM and the report shows recent updates.',
                'Add third-party patching', 'security', 300],
            ['Endpoints', 'Every device runs a supported operating system', 'high', 'os_supported', 'ep_lifecycle,vuln_patch_os',
                'Unsupported systems get no security fixes.',
                'Align checks this from the device list (OS support dates).',
                'Replace or upgrade unsupported devices', 'hardware', null],
            ['Endpoints', 'Laptops encrypted (BitLocker / FileVault)', 'high', null, 'ep_encryption,data_encrypt_rest',
                'A lost laptop isn\'t a data breach.',
                'Check the RMM or Intune encryption report for every laptop; recovery keys are stored.',
                'Encrypt every laptop', 'security', 200],
            ['Endpoints', 'Hardware within its lifecycle', 'medium', 'hw_lifecycle', 'ep_lifecycle,asset_hw_inventory',
                'Old hardware fails more often and slows people down.',
                'Align checks this from the device list and the lifecycle policy (Settings → Planning & lifecycle).',
                'Replace hardware past its lifecycle', 'hardware', null],
            ['Endpoints', 'Every device reporting in to the RMM', 'medium', 'stale', 'asset_hw_inventory',
                'A device we can\'t see is a device we can\'t patch or protect.',
                'Align checks this from the RMM\'s last check-in times.',
                'Find and re-enroll silent devices', 'project', 150],
            ['Endpoints', 'Servers and network gear under warranty', 'medium', 'warranty', 'ep_lifecycle,asset_hw_inventory',
                'A failure gets a replacement part next day, not next month.',
                'Align checks this from warranty dates on servers and network devices.',
                'Renew warranties on servers and network gear', 'hardware', null],
            ['Backup & recovery', 'Servers and Microsoft 365 backed up daily', 'critical', 'backups', 'data_backup',
                'Lost or encrypted data can be brought back.',
                'Align checks servers without a backup and failed jobs from the backup product; confirm Microsoft 365 is covered.',
                'Set up daily backups for every server and Microsoft 365', 'backup', 800],
            ['Backup & recovery', 'An offsite copy that can\'t be changed or deleted', 'critical', null, 'data_backup_offsite',
                'Ransomware can\'t delete the last good copy.',
                'Confirm a copy goes offsite to immutable or offline storage, and how long it\'s kept.',
                'Add an immutable offsite backup copy', 'backup', 1500],
            ['Backup & recovery', 'Restore tested and written up in the last 6 months', 'high', null, 'data_restore_test,bc_test',
                'We know the backups actually work when they\'re needed.',
                'Look for the last restore test write-up: what was restored, how long it took.',
                'Run and document a restore test', 'backup', 350],
            ['Network', 'Business firewall with current firmware and support', 'high', 'warranty', 'net_firewall,ep_lifecycle',
                'The front door keeps getting security updates.',
                'Check the firewall\'s support or license end date and firmware version.',
                'Replace the firewall', 'infrastructure', 2400],
            ['Network', 'No remote desktop or admin pages open to the internet', 'critical', null, 'cfg_ports_services,net_firewall,net_remote_access',
                'Open remote desktop is a top way ransomware gets in.',
                'Review firewall port forwards and run an external port scan of the office\'s public addresses.',
                'Close exposed remote-access ports', 'security', 200],
            ['Network', 'Guest Wi-Fi kept apart from the business network', 'medium', null, 'net_wireless,net_segmentation',
                'Visitors\' devices can\'t reach company systems.',
                'Join the guest network and confirm business devices and printers can\'t be reached.',
                'Separate guest Wi-Fi', 'infrastructure', 350],
            ['Network', 'DNS / web filtering on every device', 'medium', null, 'net_dns_filter',
                'Known bad sites are blocked before anything loads.',
                'Compare the DNS filter\'s device count with the RMM\'s.',
                'Add DNS filtering', 'security', null],
            ['Network', 'Battery backup (UPS) on servers and core network gear', 'medium', null, 'phys_environment',
                'A power blip doesn\'t take the office offline or corrupt a server.',
                'Check each server and the core switch and firewall are on a UPS with a battery under 4 years old.',
                'Install or replace UPS units', 'hardware', 900],
            ['Email & Microsoft 365', 'Advanced email filtering (phishing, impersonation)', 'high', null, 'email_filter',
                'Fewer phishing emails reach people at all.',
                'Confirm the mail filter (or Defender for Office 365) has anti-phishing and impersonation protection on.',
                'Add advanced email filtering', 'security', null],
            ['Email & Microsoft 365', 'SPF, DKIM and DMARC set up (DMARC at quarantine or reject)', 'high', null, 'email_auth',
                'Nobody can send email pretending to be the company.',
                'Look up the domain\'s SPF, DKIM and DMARC records; DMARC policy should be quarantine or reject.',
                'Set up SPF, DKIM and DMARC', 'cloud', 300],
            ['Email & Microsoft 365', 'Legacy sign-in blocked in Microsoft 365', 'high', 'm365_legacy_blocked', 'cloud_config,iam_mfa',
                'Old sign-in methods skip MFA entirely.',
                'Check a Conditional Access policy blocks legacy authentication, and sign-in logs show none.',
                'Block legacy authentication', 'cloud', 200],
            ['Email & Microsoft 365', 'Alerts on new mail forwarding rules', 'medium', null, 'log_review,cloud_config',
                'A hijacked mailbox quietly forwarding mail gets noticed fast.',
                'Confirm an alert policy for forwarding and inbox rules is on and goes to someone who reads it.',
                'Turn on forwarding alerts', 'cloud', 100],
            ['People & process', 'Security awareness training at least yearly', 'high', null, 'awareness_training',
                'People spot scams before they click.',
                'Check training completion for the last 12 months.',
                'Start yearly security training', 'training', 600],
            ['People & process', 'Phishing tests at least quarterly', 'medium', null, 'awareness_phishing',
                'Practice keeps the training fresh.',
                'Check the phishing test history for the last two quarters.',
                'Run quarterly phishing tests', 'training', null],
            ['People & process', 'Written incident response plan, reviewed yearly', 'high', null, 'ir_plan',
                'Everyone knows who to call and what to do when something goes wrong.',
                'Look for the plan, its contact list and the date it was last reviewed.',
                'Write an incident response plan', 'compliance', 750],
            ['People & process', 'Payment and bank changes confirmed by phone call-back', 'high', null, 'pay_verification',
                'Stops the most common invoice and wire fraud.',
                'Ask the office manager how a vendor\'s new bank details are confirmed; is it written down?',
                'Put a call-back rule in place', 'training', null],
            ['Continuity & documentation', 'Disaster recovery plan with agreed recovery times', 'high', null, 'bc_plan,bc_test',
                'Everyone agrees how quickly systems must come back after an outage.',
                'Look for a written plan with recovery time and data-loss targets the client signed off on.',
                'Write a disaster recovery plan', 'backup', 1200],
            ['Continuity & documentation', 'Network documentation current (diagram, credentials in the vault)', 'medium', null, 'asset_hw_inventory,cfg_baseline',
                'Any technician can help quickly, even in an emergency.',
                'Check the network diagram and credentials were updated in the last 12 months.',
                'Update network documentation', 'project', 400],
            ['Continuity & documentation', 'Line-of-business software on a supported version', 'medium', null, 'vuln_patch_apps,asset_sw_inventory',
                'The vendor can help when something breaks, and security fixes keep coming.',
                'Check each main business application\'s version against the vendor\'s supported list.',
                'Upgrade line-of-business software', 'software', null],
            ['Continuity & documentation', 'Domain names auto-renew with registrar lock', 'medium', null, null,
                'The website and email can\'t lapse or be taken over.',
                'Check auto-renew, registrar lock and who owns the registrar account.',
                'Lock and auto-renew domains', 'project', 50],
            ['Continuity & documentation', 'Cyber insurance policy in place and current', 'medium', null, 'gov_risk_treatment',
                'A serious incident doesn\'t become a financial disaster.',
                'Ask for the policy\'s renewal date and coverage limits; note any security requirements it lists.',
                'Review cyber insurance coverage', 'compliance', null],
            ['Continuity & documentation', 'Technology budget agreed for the year', 'low', null, 'gov_review',
                'No surprise bills: replacements and projects are planned.',
                'Check this year\'s budget in Align was reviewed with the client.',
                'Agree this year\'s technology budget', 'project', null],
        ];
    }
}
